<?php

declare(strict_types=1);

namespace Database\Seeders\Japanese;

use Database\Seeders\Concerns\SeedsLearningContent;
use Illuminate\Database\Seeder;

/**
 * Japanese reading practice (読解) — 20 Indonesian folk tales retold in
 * Japanese, at JLPT levels N5-N3. 17 of them are also retold in English by
 * LearningContentSeeder::readingStories(), so learners get the same story in
 * both languages; `translated_content` is an independent Indonesian retelling
 * for each entry rather than a shared string between the two languages.
 */
class ReadingSeeder extends Seeder
{
    use SeedsLearningContent;

    public function run(): void
    {
        $stories = $this->stories();
        $count = $this->fill('membaca-jepang', $stories);

        $this->command?->info('  membaca: '.$count.' kosakata glosarium ('.count($stories).' cerita)');
    }

    /** @param array<int, array<string, mixed>> $rows */
    private function glossary(array $rows): array
    {
        return array_map(fn (array $r) => [
            'term' => $r[0],
            'reading' => $r[1],
            'romaji' => $r[2],
            'meaning' => $r[3],
            'extra' => ['type' => 'glossary'],
        ], $rows);
    }

    private function stories(): array
    {
        return [
            [
                'title' => 'マリン・クンダン',
                'slug' => 'membaca-jepang-malin-kundang',
                'level' => 'N4',
                'summary' => '親の愛を忘れて石になった、西スマトラの親不孝な息子の伝説。',
                'minutes' => 14,
                'xp' => 30,
                'content' => "昔々、西スマトラの海の近くの小さな村に、貧しい女性とその息子マリン・クンダンが住んでいました。マリンの父はマリンが赤ちゃんの時に亡くなったので、母は魚を取って売り、一人息子を育てるために一生懸命働きました。\n\nマリンは強くて賢い青年に育ちました。ある日、彼は母に、もっと良い生活を探すために遠い町へ船で行きたいと言いました。母は行ってほしくありませんでしたが、マリンは譲りませんでした。「お金持ちになって帰ってきます、お母さん」と彼は約束しました。「私たちの生活をもっと良くします。」悲しい気持ちで、母は彼を大きな船に乗せ、見送りました。\n\n何年も過ぎましたが、マリンは帰ってきませんでした。彼は町で一生懸命働き、少しずつ成功しました。美しくて裕福な女性と結婚し、自分の船を持つ裕福な商人になりました。しかし、マリンは一度も母に手紙を書きませんでした。\n\nある日、マリンの船が故郷の村の近くの港に着きました。裕福な商人が来たと聞いた年老いた母は、息子かもしれないと思い、急いで港へ行きました。立派な服を着て甲板に立つマリンを見て、母はすぐに彼だとわかり、喜んで名前を呼びながら走り寄りました。\n\nしかし、マリンは恥ずかしく思いました。この貧しくてぼろを着た年老いた女性が自分の母だと、上品な妻や船員たちに知られたくありませんでした。「あっちへ行け、おばあさん!」と彼は叫びました。「私にはあなたのような母親はいません!」彼は母を突き飛ばし、船員に出港を命じました。\n\n心が張り裂けたマリンの母は、砂の上に膝をつきました。目には涙があふれ、心は怒りでいっぱいになりました。彼女は空に向かって手を上げ、祈りました。「もし彼が本当に私の息子でないなら、無事に行かせてください。しかし、もし彼が私の息子なら、神様、彼の冷たさと傲慢さを罰してください。」\n\n母が祈り終えるとすぐに、空は暗くなりました。雷が鳴り響き、恐ろしい嵐がマリンの船を襲いました。波が甲板に打ちつけ、帆を引き裂きました。マリンは自分の過ちに気づきましたが、もう遅すぎました。「お母さん、許してください!」彼は嵐の中で叫びましたが、もう遅すぎました。\n\n船は壊れ、マリンの体は少しずつ石に変わっていきました、まさにその浜辺で。今でも、西スマトラの海岸には、壊れた船とひざまずく男の形をした岩を見ることができると言われています。母の愛を忘れた子どもに何が起こるかを、私たちに教えてくれます。",
                'translated_content' => "Dahulu kala, di sebuah desa kecil di tepi laut Sumatera Barat, hiduplah seorang perempuan miskin bersama anaknya, Malin Kundang. Ayah Malin telah meninggal sejak ia masih bayi, sehingga ibunya bekerja sangat keras, menangkap ikan dan menjualnya, hanya untuk menghidupi anak semata wayangnya.\n\nMalin tumbuh menjadi pemuda yang kuat dan cerdas. Suatu hari, ia berkata kepada ibunya bahwa ia ingin berlayar ke kota yang jauh untuk mencari kehidupan yang lebih baik. Ibunya tidak ingin ia pergi, tetapi Malin bersikeras. \"Aku akan pulang dengan kaya, Ibu,\" janjinya. \"Aku akan membuat hidup kita lebih baik.\" Dengan hati berat, sang ibu mengizinkannya naik ke sebuah kapal besar dan berlayar pergi.\n\nBertahun-tahun berlalu, dan Malin tak kunjung kembali. Ia bekerja keras di kota, dan perlahan-lahan menjadi sukses. Ia menikahi seorang perempuan cantik dan kaya, lalu menjadi saudagar kaya dengan kapal miliknya sendiri. Namun, Malin tidak pernah sekali pun menulis surat kepada ibunya.\n\nSuatu hari, kapal Malin merapat di sebuah pelabuhan dekat desa asalnya. Ibunya yang sudah tua mendengar bahwa seorang saudagar kaya telah tiba, dan ia bergegas ke pelabuhan, berharap itu adalah anaknya. Ketika melihat Malin berdiri di geladak dengan pakaian bagus, ia langsung mengenalinya dan berlari ke arahnya sambil memanggil namanya dengan gembira.\n\nNamun Malin merasa malu. Ia tidak ingin istrinya yang anggun dan para awak kapalnya tahu bahwa perempuan tua yang miskin dan compang-camping itu adalah ibunya. \"Pergi dariku, perempuan tua!\" teriaknya. \"Aku tidak pernah punya ibu sepertimu!\" Ia mendorong ibunya dan memerintahkan anak buahnya untuk berlayar pergi.\n\nDengan hati yang hancur, ibu Malin jatuh berlutut di atas pasir. Air mata memenuhi matanya, dan amarah memenuhi hatinya. Ia mengangkat tangannya ke langit dan berdoa. \"Jika ia benar-benar bukan anakku, biarkan ia pergi dengan selamat. Tetapi jika ia memang anakku, ya Tuhan, hukumlah ia atas kekejaman dan kesombongannya.\"\n\nBelum lama ia selesai berdoa, langit tiba-tiba menjadi gelap. Guntur menggelegar, dan badai dahsyat menghantam kapal Malin. Ombak menerjang geladak, merobek layar-layarnya. Malin menyadari kesalahannya, tetapi sudah terlambat. \"Maafkan aku, Ibu!\" teriaknya di tengah badai, namun semuanya sudah terlambat.\n\nKapal itu hancur, dan tubuh Malin perlahan-lahan berubah menjadi batu, tepat di pantai itu. Hingga kini, orang-orang berkata bahwa kita masih bisa melihat batu berbentuk kapal yang hancur dan seorang pria yang berlutut di pesisir Sumatera Barat — sebuah pengingat akan apa yang terjadi pada anak yang melupakan kasih sayang ibunya.",
                'items' => $this->glossary([
                    ['貧しい', 'まずしい', 'mazushii', 'miskin'],
                    ['一生懸命', 'いっしょうけんめい', 'isshoukenmei', 'bersungguh-sungguh, sekuat tenaga'],
                    ['裕福', 'ゆうふく', 'yuufuku', 'kaya raya'],
                    ['恥ずかしく', 'はずかしく', 'hazukashiku', 'malu (bentuk kamus: 恥ずかしい)'],
                    ['ぼろ', 'ぼろ', 'boro', 'compang-camping, lusuh'],
                    ['心が張り裂けた', 'こころがはりさけた', 'kokoro ga harisaketa', 'hati hancur, patah hati'],
                    ['傲慢', 'ごうまん', 'gouman', 'sombong'],
                ]),
            ],
            [
                'title' => 'バワン・メラーとバワン・プティ',
                'slug' => 'membaca-jepang-bawang-merah-dan-bawang-putih',
                'level' => 'N4',
                'summary' => '優しい心を持つ娘と、欲張りな義理の姉についての民話。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔々、バワン・プティという優しい女の子がいました。母親が亡くなった後、父親はバワン・メラーという娘がいる女性と再婚しました。継母と義理の姉は怠け者で意地悪で、料理から川での洗濯まで、すべての家事をバワン・プティにさせました。\n\nある日、洗濯をしている時、バワン・プティはうっかり継母のお気に入りのスカーフを川に落としてしまいました。彼女は川岸に沿って水の流れを追いかけ、小さな小屋に住むおばあさんを見つけました。「おばあさん、スカーフが流れてくるのを見ませんでしたか?」バワン・プティは丁寧に尋ねました。\n\nおばあさんはスカーフを持っていると言いましたが、まずバワン・プティに家事を手伝ってほしいと頼みました。バワン・プティは一度も文句を言わずに、喜んで掃除や料理を手伝いました。彼女の優しさに満足したおばあさんはスカーフを返し、大きいのと小さいの、二つのかぼちゃを贈り物として差し出しました。「どちらか一つを選びなさい」とおばあさんは言いました。謙虚なバワン・プティは小さいかぼちゃを選びました。\n\n家に帰って小さいかぼちゃを切ってみると、中には金や宝石、美しい服がいっぱい入っていて驚きました!継母とバワン・メラーはその宝物を見て、驚きと嫉妬でいっぱいになりました。\n\n次の日、バワン・メラーは自分で川へ行き、わざとスカーフを水に投げ入れました。同じおばあさんを見つけると、家事を手伝うことも拒み、乱暴にスカーフを返すよう要求しました。それでもおばあさんは同じように、大きいかぼちゃか小さいかぼちゃかを選ばせました。欲張りなことしか考えていないバワン・メラーは、お礼も言わずに大きいかぼちゃをつかみました。\n\n家に帰ったバワン・メラーは、義理の妹よりもっとたくさんの宝物を期待して、急いで大きいかぼちゃを切りました。しかし出てきたのは危険な蛇と虫でした!遅すぎましたが、彼女は優しさと謙虚さが欲張りよりもずっと価値があることを学びました。",
                'translated_content' => "Pada zaman dahulu, hiduplah seorang gadis baik hati bernama Bawang Putih. Setelah ibunya meninggal, ayahnya menikah lagi dengan seorang perempuan yang sudah memiliki seorang anak perempuan bernama Bawang Merah. Ibu tiri dan saudara tirinya itu pemalas dan tidak baik hati, dan mereka memaksa Bawang Putih mengerjakan semua pekerjaan rumah, mulai dari memasak hingga mencuci pakaian di sungai.\n\nSuatu hari, saat sedang mencuci pakaian, Bawang Putih tanpa sengaja menjatuhkan selendang kesayangan ibu tirinya ke sungai. Ia mengikuti aliran air di sepanjang tepi sungai hingga menemukan seorang nenek tua yang tinggal di sebuah gubuk kecil. \"Nek, apakah Nenek melihat selendang yang hanyut?\" tanya Bawang Putih dengan sopan.\n\nNenek itu berkata bahwa ia menyimpan selendang tersebut, tetapi terlebih dahulu meminta Bawang Putih membantunya mengerjakan beberapa pekerjaan rumah. Bawang Putih dengan senang hati membantu membersihkan rumah dan memasak, tanpa mengeluh sedikit pun. Karena senang dengan kebaikannya, nenek itu mengembalikan selendangnya dan menawarkan hadiah: dua buah labu, satu besar dan satu kecil. \"Pilihlah salah satu,\" kata nenek itu. Bawang Putih, karena rendah hati, memilih labu yang kecil.\n\nKetika ia pulang dan membelah labu kecil itu, ia sangat terkejut mendapati labu itu penuh dengan emas, perhiasan, dan pakaian indah! Ibu tiri dan Bawang Merah terkejut sekaligus iri hati saat melihat harta itu.\n\nKeesokan harinya, Bawang Merah pergi sendiri ke sungai dan sengaja membuang selendang itu ke air. Ia menemukan nenek yang sama dan meminta selendangnya kembali dengan kasar, menolak membantu pekerjaan apa pun. Meski begitu, nenek itu tetap menawarkan pilihan yang sama: labu besar atau labu kecil. Bawang Merah, yang hanya memikirkan keserakahan, langsung mengambil labu besar tanpa mengucapkan terima kasih.\n\nSetibanya di rumah, Bawang Merah dengan tidak sabar membelah labu besar itu, berharap mendapat harta yang lebih banyak daripada saudara tirinya. Namun yang keluar justru ular-ular dan serangga berbahaya! Ia pun menyadari, meski sudah terlambat, bahwa kebaikan hati dan kerendahan hati jauh lebih berharga daripada keserakahan.",
                'items' => $this->glossary([
                    ['継母', 'ままはは', 'mamahaha', 'ibu tiri'],
                    ['怠け者', 'なまけもの', 'namakemono', 'pemalas'],
                    ['川岸', 'かわぎし', 'kawagishi', 'tepi sungai'],
                    ['謙虚', 'けんきょ', 'kenkyo', 'rendah hati'],
                    ['嫉妬', 'しっと', 'shitto', 'iri hati'],
                    ['欲張り', 'よくばり', 'yokubari', 'serakah'],
                ]),
            ],
            [
                'title' => 'ティムン・マス',
                'slug' => 'membaca-jepang-timun-mas',
                'level' => 'N4',
                'summary' => '魔法の袋を使って鬼から逃げる、中部ジャワの少女の伝説。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "中部ジャワの小さな村に、子どものいないモボック・シルニというおばあさんが住んでいました。ある夜、彼女は森に住む鬼に子どもを授けてくださいと祈りました。鬼は魔法のきゅうりの種をあげることに同意しましたが、一つの条件がありました。子どもが十七歳になったら、鬼に返して食べさせなければならないというものでした。\n\nモボック・シルニが種を植えると、すぐに大きな金色のきゅうりが育ちました。中を開けると、美しい赤ちゃんの女の子がいました。彼女はその子を「ティムン・マス(黄金のきゅうり)」と名付けました。ティムン・マスは健康で賢く優しい子に育ち、モボック・シルニは彼女を深く愛しながらも、鬼が戻ってくる日を恐れていました。\n\nティムン・マスが十七歳になった時、鬼が腹を空かせてうなりながら戻ってきました。恐ろしくなったモボック・シルニは、ティムン・マスを森へ逃がし、四つの魔法の袋を渡しました。きゅうりの種、針、塩、エビのペーストです。「鬼が追いついたら、これを後ろに投げなさい」と彼女は言いました。\n\n鬼は森の中でティムン・マスを追いかけました。近づいてきた時、彼女はきゅうりの種を後ろに投げました。たちまち広いきゅうり畑が広がり、鬼はそれを食べながら進まなければならず、遅くなりました。しかし、すぐにまた追いついてきました。\n\n次にティムン・マスは針を投げると、鋭いとげのある竹林に変わり、鬼の足を傷つけました。それでも鬼は突き進み、追いかけ続けました。\n\nそれからティムン・マスは塩を投げると、後ろに広くて深い海が現れ、泳いで渡らなければならない鬼をさらに遅くしました。ついに疲れ果てて追い詰められたティムン・マスは、エビのペーストを投げました。それは熱い泥の煮え立つ湖に変わりました。止まりきれなかった鬼は泥の中に落ち、沈んで永遠に姿を消しました。\n\n無事に助かったティムン・マスは母のもとへ帰り、二人はその後ずっと幸せに暮らしました。",
                'translated_content' => "Di sebuah desa kecil di Jawa Tengah, hiduplah seorang perempuan tua bernama Mbok Sirni yang tidak memiliki anak. Pada suatu malam, ia berdoa kepada seorang raksasa yang tinggal di hutan agar diberikan seorang anak. Raksasa itu setuju memberinya sebutir biji mentimun ajaib, dengan satu syarat: ketika anak itu berusia tujuh belas tahun, ia harus diserahkan kembali kepada sang raksasa untuk dimakan.\n\nMbok Sirni menanam biji itu, dan tak lama kemudian tumbuhlah sebuah mentimun raksasa berwarna keemasan. Di dalamnya, ia menemukan seorang bayi perempuan yang cantik. Ia menamainya Timun Mas, yang berarti \"Mentimun Emas\". Timun Mas tumbuh menjadi anak yang sehat, cerdas, dan baik hati, dan Mbok Sirni sangat menyayanginya, sambil terus mencemaskan hari ketika raksasa itu akan kembali.\n\nKetika Timun Mas berusia tujuh belas tahun, raksasa itu kembali, mengaum kelaparan. Ketakutan, Mbok Sirni menyuruh Timun Mas berlari ke dalam hutan, sambil memberinya empat kantong ajaib: biji mentimun, jarum, garam, dan terasi udang. \"Lemparkan ini ke belakangmu jika raksasa itu berhasil mengejarmu,\" katanya.\n\nRaksasa itu mengejar Timun Mas melintasi hutan. Ketika ia hampir tertangkap, Timun Mas melemparkan biji mentimun ke belakangnya. Seketika, tumbuhlah ladang tanaman mentimun yang luas, memperlambat raksasa itu karena ia harus memakan jalan keluarnya. Namun tak lama kemudian ia berhasil mengejar lagi.\n\nSelanjutnya, Timun Mas melemparkan jarum-jarum itu, dan seketika berubah menjadi hutan bambu lebat dengan duri-duri tajam, melukai kaki raksasa itu. Meski begitu, raksasa itu tetap menerobos dan terus mengejarnya.\n\nKemudian Timun Mas melemparkan garam, dan munculah lautan luas nan dalam di belakangnya, membuat raksasa itu semakin lambat karena harus bersusah payah berenang menyeberang. Akhirnya, dengan kelelahan dan putus asa, Timun Mas melemparkan terasi udang. Terasi itu berubah menjadi danau lumpur panas yang mendidih. Raksasa itu, yang tidak sempat berhenti, terjatuh ke dalam lumpur dan tenggelam di dalamnya, lenyap untuk selamanya.\n\nAkhirnya selamat, Timun Mas pulang ke rumah menemui ibunya, dan mereka hidup bahagia bersama untuk selamanya.",
                'items' => $this->glossary([
                    ['鬼', 'おに', 'oni', 'raksasa'],
                    ['条件', 'じょうけん', 'jouken', 'syarat'],
                    ['恐ろしく', 'おそろしく', 'osoroshiku', 'menakutkan (bentuk kamus: 恐ろしい)'],
                    ['追いかけ', 'おいかけ', 'oikake', 'mengejar (bentuk kamus: 追いかける)'],
                    ['とげ', 'とげ', 'toge', 'duri'],
                    ['疲れ果て', 'つかれはて', 'tsukarehate', 'sangat kelelahan (bentuk kamus: 疲れ果てる)'],
                ]),
            ],
            [
                'title' => 'サンクリアン',
                'slug' => 'membaca-jepang-sangkuriang',
                'level' => 'N3',
                'summary' => '息子が知らずに実の母に恋をし、最後に激怒して山を蹴り倒したという、西ジャワのタンクバンプラフ山の伝説。',
                'minutes' => 15,
                'xp' => 30,
                'content' => "昔、西ジャワにダヤン・スンビという美しい王女が住んでいました。ある日、彼女が布を織っていると、糸を巻く道具が床に落ちてしまいました。うんざりした彼女は、思わず「これを拾ってくれた者がいたら、男なら夫に、女なら姉妹にしよう」と口にしてしまいます。すると、一匹の雄犬トゥマンがそれを拾って持ってきました。実はこのトゥマンは、天罰によって犬の姿に変えられた神でした。約束を破るわけにはいかず、ダヤン・スンビはやむを得ずトゥマンと結婚することになったのです。\n\nマリンは強くて賢い青年に育ちました。ある日、彼は母に、もっと良い生活を探すために遠い町へ船で行きたいと言いました。二人の間には男の子が生まれ、サンクリアンと名付けられました。サンクリアンは、トゥマンが実の父であることを知らないまま、ただの飼い犬として大切に育てていました。彼は狩りが得意な、たくましい少年に成長しました。\n\nある日、サンクリアンは森へ狩りに出かけ、トゥマンを連れて行きました。しかし、獲物のイノシシを見つけても、トゥマンはどうしても動こうとしません。腹を立てたサンクリアンは、とうとうトゥマンを殺してしまいました。そして、そのことを知らせないまま、犬の肝臓を持ち帰り、母に料理として食べさせてしまったのです。\n\n後になって、ダヤン・スンビはその肉が愛犬トゥマン、つまり自分の夫のものだったと知り、深い悲しみと怒りに襲われました。彼女はご飯をよそうしゃもじでサンクリアンの頭を強く叩き、傷を負わせると、家から追い出してしまいました。\n\nサンクリアンは当てもなくさまよい、各地を旅しながら年月を過ごし、やがて逞しく勇敢な青年へと成長しました。一方、ダヤン・スンビは深く祈り続けたことで神々から永遠の若さと美しさを授かり、何年経っても少女のような姿のままでした。\n\n長い年月の後、サンクリアンは自分が生まれた土地とは知らずにその村へ戻ってきました。そこで彼はダヤン・スンビと出会い、互いにひと目で恋に落ち、結婚を約束します。ところが、ある日ダヤン・スンビは彼の頭にある古い傷跡に気づき、彼が自分の息子であることを悟りました。彼女は必死に結婚をやめさせようとしましたが、サンクリアンは聞き入れません。そこでダヤン・スンビは一つの条件を出しました。「一晩のうちに、川をせき止めて湖を作り、その上に立派な船を完成させてください」。\n\nサンクリアンは不思議な力を持つ精霊たちを呼び寄せ、驚くべき速さで作業を進めました。夜明けが近づく頃には、湖も船もほとんど完成しつつありました。焦ったダヤン・スンビは、東の空に赤い布を広げさせ、村人たちに早朝から米をつかせて、まるで太陽が昇ったかのように見せかけました。それを見た精霊たちは夜が明けたと勘違いして恐れをなし、仕事を放り出して逃げ去ってしまいました。\n\n夜明け前に船が完成しないと知ったサンクリアンは激しく怒り、未完成の船を思い切り蹴り飛ばしました。船はひっくり返って山となり、これが今も西ジャワに残るタンクバンプラフ山だと言われています。「タンクバンプラフ」とは「ひっくり返った船」という意味で、逃げるダヤン・スンビを追いかけたサンクリアンの伝説とともに、今も語り継がれています。",
                'translated_content' => "Dahulu kala, di Jawa Barat hiduplah seorang putri cantik bernama Dayang Sumbi. Suatu hari, ketika ia sedang menenun kain, alat pemintal benangnya jatuh ke lantai. Karena jengkel, tanpa sadar ia berkata, \"Siapa pun yang mengambilkannya untukku, jika laki-laki akan kujadikan suami, jika perempuan akan kujadikan saudara.\" Seekor anjing jantan bernama Tumang lalu mengambilkan alat itu untuknya. Ternyata, Tumang adalah seorang dewa yang dikutuk menjadi anjing sebagai hukuman dari langit. Karena tidak bisa mengingkari janjinya, Dayang Sumbi terpaksa menikah dengan Tumang.\n\nDari pernikahan itu lahirlah seorang anak laki-laki yang diberi nama Sangkuriang. Tanpa mengetahui bahwa Tumang adalah ayah kandungnya, Sangkuriang membesarkannya dengan penuh kasih sayang sebagai anjing peliharaan biasa. Ia tumbuh menjadi anak laki-laki yang kekar dan pandai berburu.\n\nSuatu hari, Sangkuriang pergi berburu ke hutan dengan mengajak Tumang. Namun, ketika seekor babi hutan muncul, Tumang sama sekali tidak mau bergerak. Sangkuriang yang marah akhirnya membunuh Tumang. Tanpa memberi tahu ibunya, ia membawa pulang hati anjing itu dan memberikannya sebagai masakan untuk sang ibu.\n\nBelakangan, Dayang Sumbi mengetahui bahwa daging yang ia makan adalah daging Tumang, anjing kesayangannya sekaligus suaminya. Ia diliputi kesedihan dan kemarahan yang mendalam. Ia memukul kepala Sangkuriang dengan centong nasi hingga terluka, lalu mengusirnya dari rumah.\n\nSangkuriang mengembara tanpa tujuan, menghabiskan waktu bertahun-tahun mengelilingi berbagai daerah, hingga akhirnya tumbuh menjadi pemuda yang gagah dan pemberani. Sementara itu, karena terus berdoa, Dayang Sumbi dianugerahi keabadian muda dan kecantikan oleh para dewa, sehingga meskipun bertahun-tahun berlalu, ia tetap terlihat seperti gadis muda.\n\nBertahun-tahun kemudian, Sangkuriang kembali ke desa tempat ia dilahirkan tanpa menyadarinya. Di sana ia bertemu Dayang Sumbi, dan keduanya saling jatuh cinta pada pandangan pertama lalu berjanji akan menikah. Namun, suatu hari Dayang Sumbi menyadari ada bekas luka lama di kepala Sangkuriang, dan ia pun sadar bahwa pemuda itu adalah anak kandungnya sendiri. Ia berusaha sekuat tenaga menggagalkan pernikahan itu, tetapi Sangkuriang tidak mau mendengarkan. Maka Dayang Sumbi pun mengajukan sebuah syarat, \"Dalam satu malam, bendunglah sungai untuk membuat sebuah danau, dan selesaikanlah sebuah perahu yang megah di atasnya.\"\n\nSangkuriang memanggil para makhluk halus yang memiliki kekuatan gaib, dan pekerjaan itu pun berjalan dengan kecepatan luar biasa. Menjelang fajar, danau dan perahu itu hampir selesai. Dayang Sumbi yang panik segera menyuruh orang membentangkan kain merah di langit timur dan meminta warga desa menumbuk padi sejak dini hari, sehingga tampak seolah-olah matahari telah terbit. Melihat hal itu, para makhluk halus mengira hari sudah pagi, ketakutan, lalu meninggalkan pekerjaan mereka dan melarikan diri.\n\nMengetahui perahu itu tidak selesai sebelum fajar, Sangkuriang menjadi sangat marah dan menendang perahu yang belum jadi itu sekuat tenaga. Perahu itu terbalik dan berubah menjadi gunung, yang hingga kini dikenal sebagai Gunung Tangkuban Perahu di Jawa Barat. \"Tangkuban Perahu\" berarti \"perahu yang terbalik\", dan bersama kisah Sangkuriang yang mengejar Dayang Sumbi yang melarikan diri, legenda ini terus diwariskan hingga sekarang.",
                'items' => $this->glossary([
                    ['織って', 'おって', 'otte', 'menenun'],
                    ['うんざり', 'うんざり', 'unzari', 'jengkel, bosan'],
                    ['天罰', 'てんばつ', 'tenbatsu', 'hukuman dari langit'],
                    ['たくましい', 'たくましい', 'takumashii', 'kekar, tangguh'],
                    ['腹を立てた', 'はらをたてた', 'hara wo tateta', 'marah'],
                    ['しゃもじ', 'しゃもじ', 'shamoji', 'centong nasi'],
                    ['せき止めて', 'せきとめて', 'sekitomete', 'membendung'],
                    ['蹴り飛ばしました', 'けりとばしました', 'keritobashimashita', 'menendang dengan keras'],
                ]),
            ],
            [
                'title' => 'トバ湖',
                'slug' => 'membaca-jepang-danau-toba',
                'level' => 'N4',
                'summary' => '妻との約束を破ってしまった漁師の悲しい物語から生まれた、北スマトラの美しい湖の伝説。',
                'minutes' => 13,
                'xp' => 30,
                'content' => "昔、北スマトラのある村に、トバという名前の貧しい若者が住んでいました。彼は毎日川で魚を釣って生活していました。ある日、いつものように釣りをしていると、とても大きくて金色に光る魚がかかりました。\n\nトバはその魚を家に持って帰り、料理をしようとしました。しかし、台所に魚を置いてほかの用事をして戻ってくると、なんと魚は美しい女性に変わっていたのです。女性は「私は神様に魚の姿に変えられていましたが、今、元の姿に戻ることができました」と言いました。そして、「もし私と結婚してくれるなら、一つだけ約束してください。私が魚だったことを、決して誰にも話さないでください」と頼みました。トバはその約束を守ると誓い、二人は結婚しました。\n\n二人はやがて男の子を授かり、サモシールと名付けました。サモシールは元気に育ちましたが、いつもお腹をすかせていて、家族全員分の食べ物を一人で食べてしまうことがよくありました。\n\nある日、母はサモシールに、畑で働く父のために昼ご飯を届けるよう頼みました。しかし、畑へ向かう途中でお腹がすいたサモシールは、我慢できずに父のためのお弁当を全部一人で食べてしまいました。\n\nお昼になって、お腹をすかせたトバが畑から家に帰ってきましたが、お弁当はどこにもありません。理由を聞かれたサモシールは、正直に「僕が全部食べてしまいました」と答えました。それを聞いたトバは、あまりの怒りに我を忘れ、思わず「お前は本当に魚の子どもだ!」と叫んでしまいました。\n\nその言葉を口にした瞬間、空は急に暗くなり、大地が激しく揺れ始めました。そして、母と息子が立っていた場所から水が勢いよく湧き出し、あたり一面をあっという間に飲み込んでいきました。母と息子の姿は、二度と見られなくなってしまいました。\n\n湧き出た水はどんどん増え続け、やがて谷全体を覆う大きな湖になりました。人々はこの湖を、トバの名前にちなんでトバ湖と呼ぶようになりました。そして、湖の真ん中にできた島は、息子の名前をとってサモシール島と名付けられました。この伝説は、約束を守ることの大切さを教えるものとして、今も語り継がれています。",
                'translated_content' => "Dahulu kala, di sebuah desa di Sumatera Utara, hiduplah seorang pemuda miskin bernama Toba. Ia menyambung hidup dengan memancing ikan di sungai setiap hari. Suatu hari, seperti biasa ia sedang memancing, tiba-tiba seekor ikan besar berwarna emas yang berkilauan tersangkut di kailnya.\n\nToba membawa pulang ikan itu untuk dimasak. Namun, setelah meletakkan ikan itu di dapur dan kembali setelah mengerjakan hal lain, ternyata ikan itu telah berubah menjadi seorang perempuan yang cantik. Perempuan itu berkata, \"Aku dikutuk oleh para dewa menjadi seekor ikan, tetapi sekarang aku bisa kembali ke wujud asliku.\" Lalu ia berkata, \"Jika kau bersedia menikahiku, aku hanya meminta satu janji. Jangan pernah memberitahu siapa pun bahwa aku dulunya adalah seekor ikan.\" Toba bersumpah akan menjaga janji itu, dan mereka pun menikah.\n\nTak lama kemudian, mereka dikaruniai seorang anak laki-laki yang diberi nama Samosir. Samosir tumbuh dengan sehat, tetapi ia selalu merasa lapar, dan sering kali menghabiskan sendiri makanan yang seharusnya untuk seluruh keluarga.\n\nSuatu hari, sang ibu meminta Samosir mengantarkan makan siang untuk ayahnya yang sedang bekerja di ladang. Namun, di tengah perjalanan menuju ladang, Samosir merasa sangat lapar dan tanpa bisa menahan diri, ia menghabiskan sendiri seluruh bekal makanan untuk ayahnya.\n\nMenjelang siang, Toba yang kelaparan pulang dari ladang, tetapi bekal makanannya tidak ada di mana pun. Ketika ditanya alasannya, Samosir dengan jujur menjawab, \"Aku sudah menghabiskannya semua.\" Mendengar itu, Toba menjadi sangat marah hingga lupa diri, dan tanpa sadar berteriak, \"Kau benar-benar anak seekor ikan!\"\n\nBegitu kata-kata itu terucap, langit tiba-tiba menjadi gelap dan bumi mulai berguncang hebat. Dari tempat ibu dan anak itu berdiri, air memancar keluar dengan deras, dan dalam sekejap menenggelamkan seluruh daerah di sekitarnya. Sosok ibu dan anak itu pun tidak pernah terlihat lagi.\n\nAir yang terus memancar itu semakin lama semakin banyak, hingga akhirnya membentuk sebuah danau besar yang menutupi seluruh lembah. Orang-orang kemudian menamai danau itu Danau Toba, sesuai dengan nama sang ayah. Sementara itu, pulau yang muncul di tengah danau dinamai Pulau Samosir, sesuai dengan nama sang anak. Legenda ini terus diwariskan hingga sekarang sebagai pengajaran tentang pentingnya menepati janji.",
                'items' => $this->glossary([
                    ['釣って', 'つって', 'tsutte', 'memancing'],
                    ['かかりました', 'かかりました', 'kakarimashita', 'tersangkut, kena (pancingan)'],
                    ['授かり', 'さずかり', 'sazukari', 'dikaruniai'],
                    ['我慢できずに', 'がまんできずに', 'gaman dekizu ni', 'tidak bisa menahan diri'],
                    ['我を忘れ', 'われをわすれ', 'ware wo wasure', 'lupa diri, kehilangan kendali'],
                    ['湧き出し', 'わきだし', 'wakidashi', 'memancar keluar'],
                    ['語り継がれて', 'かたりつがれて', 'kataritsugarete', 'diwariskan turun-temurun'],
                ]),
            ],
            [
                'title' => 'ロロ・ジョングラン',
                'slug' => 'membaca-jepang-roro-jonggrang',
                'level' => 'N4',
                'summary' => '一夜で千の寺院を建てるという約束を機知で破らせた王女と、その怒りで石像に変えられてしまった中部ジャワの伝説。',
                'minutes' => 14,
                'xp' => 30,
                'content' => "昔、中部ジャワにプランバナンという豊かな王国があり、ロロ・ジョングランという美しい王女が住んでいました。彼女は王の一人娘で、多くの人々に愛されていました。\n\nある時、隣のプンギン王国の王子バンドン・ボンドウォソが、強力な軍隊と不思議な力を持つ家来たちを率いてプランバナンを攻めてきました。激しい戦いの末、プランバナンの王は命を落とし、王国はバンドン・ボンドウォソに支配されてしまいました。\n\n王国を手に入れたバンドン・ボンドウォソは、ロロ・ジョングランの美しさに心を奪われ、彼女に結婚を申し込みました。しかし、ロロ・ジョングランは父を殺した相手と結婚することなど絶対にできないと思いました。とはいえ、強い力を持つ相手に真正面から断ることもできず、彼女は考えた末にある条件を出しました。\n\n「一晩のうちに、千の寺院を建ててください。それができたら、あなたと結婚しましょう」。ロロ・ジョングランは、そんなことは誰にも不可能だと思い、この条件で結婚を諦めさせようとしたのです。\n\nところが、バンドン・ボンドウォソは不思議な力を使って、大勢の精霊たちを呼び出しました。精霊たちはものすごい速さで働き、夜が明ける前に、あと少しで千の寺院が完成しそうになっていました。\n\n驚いたロロ・ジョングランは、侍女たちを起こして助けを求めました。彼女たちは村中の女性を集めて夜中から米をつかせ、さらに東の空に近い場所でわらを燃やして、まるで朝日が昇ったかのように空を赤く見せかけました。それを見た鶏たちも朝が来たと勘違いして鳴き始めました。精霊たちは夜が明けたと信じて恐れ、まだ寺院が九百九十九しか完成していないのに、仕事を放り出して逃げてしまいました。\n\n朝になり、寺院が一つ足りないことに気づいたバンドン・ボンドウォソは、ロロ・ジョングランに騙されたことを知り、激しく怒りました。そして彼は「お前自身が最後の一つになればいい」と言って、ロロ・ジョングランを石像に変えてしまいました。\n\nこうして、ロロ・ジョングランは千番目の寺院として石像の姿のまま残ることになりました。今日でも、中部ジャワにあるプランバナン寺院群の中には、彼女の姿だと言われる石像が大切に残されており、この悲しい伝説とともに語り継がれています。",
                'translated_content' => "Dahulu kala, di Jawa Tengah terdapat sebuah kerajaan makmur bernama Prambanan, tempat tinggal seorang putri cantik bernama Roro Jonggrang. Ia adalah putri tunggal sang raja dan sangat dicintai oleh rakyatnya.\n\nPada suatu masa, Bandung Bondowoso, pangeran dari Kerajaan Pengging yang bertetangga, menyerang Prambanan dengan memimpin pasukan yang kuat serta para pengikut yang memiliki kekuatan gaib. Setelah pertempuran sengit, raja Prambanan gugur, dan kerajaan itu pun jatuh ke tangan Bandung Bondowoso.\n\nSetelah menguasai kerajaan itu, Bandung Bondowoso terpikat oleh kecantikan Roro Jonggrang dan melamarnya. Namun, Roro Jonggrang berpikir bahwa ia sama sekali tidak bisa menikah dengan orang yang telah membunuh ayahnya. Meski begitu, ia juga tidak bisa menolaknya secara langsung karena lawan yang begitu berkuasa, maka setelah berpikir panjang, ia pun mengajukan sebuah syarat.\n\n\"Bangunlah seribu candi dalam satu malam. Jika kau berhasil, aku akan menikah denganmu.\" Roro Jonggrang yakin hal itu mustahil dilakukan siapa pun, dan dengan syarat itu ia berusaha membuat Bandung Bondowoso menyerah dari niatnya untuk menikahinya.\n\nNamun, Bandung Bondowoso menggunakan kekuatan gaibnya untuk memanggil banyak makhluk halus. Para makhluk halus itu bekerja dengan kecepatan luar biasa, dan menjelang fajar, seribu candi itu hampir saja selesai dibangun.\n\nRoro Jonggrang yang terkejut segera membangunkan para dayangnya untuk meminta bantuan. Mereka mengumpulkan seluruh perempuan di desa untuk menumbuk padi sejak tengah malam, dan juga membakar jerami di dekat langit timur agar langit tampak memerah seolah-olah matahari telah terbit. Melihat itu, ayam-ayam pun mengira hari sudah pagi dan mulai berkokok. Para makhluk halus yang percaya bahwa fajar telah tiba menjadi ketakutan, dan meskipun candi yang selesai baru sembilan ratus sembilan puluh sembilan, mereka meninggalkan pekerjaan itu dan melarikan diri.\n\nKetika pagi tiba, Bandung Bondowoso menyadari bahwa kurang satu candi, dan mengetahui bahwa dirinya telah ditipu oleh Roro Jonggrang, ia pun menjadi sangat murka. Ia lalu berkata, \"Jadilah kau sendiri yang terakhir,\" dan mengutuk Roro Jonggrang menjadi sebuah arca batu.\n\nDengan demikian, Roro Jonggrang tetap tinggal sebagai candi keseribu dalam wujud arca batu. Hingga hari ini, di kompleks Candi Prambanan yang terletak di Jawa Tengah, arca yang dipercaya sebagai wujud dirinya masih tersimpan dengan baik, dan legenda yang menyedihkan ini terus diwariskan hingga sekarang.",
                'items' => $this->glossary([
                    ['攻めて', 'せめて', 'semete', 'menyerang'],
                    ['命を落とし', 'いのちをおとし', 'inochi wo otoshi', 'kehilangan nyawa'],
                    ['心を奪われ', 'こころをうばわれ', 'kokoro wo ubaware', 'terpikat hatinya'],
                    ['諦めさせよう', 'あきらめさせよう', 'akiramesaseyou', 'membuat menyerah'],
                    ['見せかけました', 'みせかけました', 'misekakemashita', 'berpura-pura terlihat seperti'],
                    ['騙された', 'だまされた', 'damasareta', 'ditipu'],
                    ['語り継がれて', 'かたりつがれて', 'kataritsugarete', 'diwariskan turun-temurun'],
                ]),
            ],
            [
                'title' => 'バトゥ・ムナンギス',
                'slug' => 'membaca-jepang-batu-menangis',
                'level' => 'N5',
                'summary' => '貧しい母を恥ずかしく思い何度も否定した娘が、石に変わってしまうという西カリマンタンの悲しい民話。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔、西カリマンタンの小さな村に、母と娘が住んでいました。母は貧しくて、毎日一生懸命働いていました。娘はとても美しかったですが、いつも怠けていて、母を全然手伝いませんでした。\n\nある日、母と娘は町へ行きました。母はいつも畑で働いているので、古くて汚れた服を着ていました。\n\n町で、一人のハンサムな青年が娘に声をかけました。そして、「隣にいる人は誰ですか」と聞きました。娘は恥ずかしくなって、「この人は私のお手伝いさんです」と嘘をつきました。母だとは言いませんでした。\n\nそれから、町を歩くたびに、いろいろな人が同じことを聞きました。娘はその度に「これは私の母ではありません、お手伝いさんです」と答えました。娘は何度も何度も母を否定しました。\n\n母はとても悲しくなりました。娘に何度も「お手伝いさん」と呼ばれて、心が痛みました。とうとう母は道にひざまずいて、神様に祈りました。「娘の心を、どうか正してください」。\n\nすると、突然、娘の足が石に変わり始めました。娘は驚いて、「お母さん、ごめんなさい」と泣きながら謝りました。しかし、もう遅すぎました。石はゆっくりと足から体全体へ広がっていきました。\n\n娘は泣きながら、少しずつ石になっていきました。最後には全身が石になってしまいましたが、その石からは今でも涙のような水が流れていると言われています。人々はこの石を「バトゥ・ムナンギス」、つまり「泣く石」と呼ぶようになりました。",
                'translated_content' => "Dahulu kala, di sebuah desa kecil di Kalimantan Barat, hiduplah seorang ibu dan anak perempuannya. Sang ibu miskin dan bekerja keras setiap hari. Anak perempuannya sangat cantik, tetapi selalu malas dan sama sekali tidak pernah membantu ibunya.\n\nSuatu hari, ibu dan anaknya pergi ke kota. Karena sang ibu selalu bekerja di ladang, ia memakai pakaian yang tua dan kotor.\n\nDi kota, seorang pemuda tampan menyapa sang anak. Ia bertanya, \"Siapa orang yang di sampingmu itu?\" Sang anak menjadi malu, lalu berbohong, \"Orang ini adalah pembantu saya.\" Ia tidak mengatakan bahwa itu adalah ibunya.\n\nSetelah itu, setiap kali mereka berjalan di kota, berbagai orang menanyakan hal yang sama. Setiap kali pula sang anak menjawab, \"Ini bukan ibu saya, ini pembantu saya.\" Berkali-kali ia menyangkal ibunya sendiri.\n\nHati sang ibu menjadi sangat sedih. Karena berkali-kali dipanggil \"pembantu\" oleh anaknya sendiri, hatinya terasa perih. Akhirnya sang ibu berlutut di jalan dan berdoa kepada Tuhan, \"Tolong perbaikilah hati anakku.\"\n\nTiba-tiba, kaki sang anak mulai berubah menjadi batu. Sang anak terkejut dan sambil menangis meminta maaf, \"Ibu, maafkan aku.\" Namun, semuanya sudah terlambat. Batu itu perlahan-lahan menyebar dari kaki ke seluruh tubuhnya.\n\nSambil menangis, sang anak perlahan-lahan berubah menjadi batu. Akhirnya seluruh tubuhnya menjadi batu, tetapi konon dari batu itu hingga kini masih mengalir air seperti air mata. Orang-orang pun menyebut batu itu \"Batu Menangis\", yang berarti \"batu yang menangis\".",
                'items' => $this->glossary([
                    ['貧しくて', 'まずしくて', 'mazushikute', 'miskin'],
                    ['一生懸命', 'いっしょうけんめい', 'isshoukenmei', 'bersungguh-sungguh'],
                    ['怠けていて', 'なまけていて', 'namaketeite', 'malas'],
                    ['恥ずかしくなって', 'はずかしくなって', 'hazukashikunatte', 'menjadi malu'],
                    ['嘘をつきました', 'うそをつきました', 'uso wo tsukimashita', 'berbohong'],
                    ['否定しました', 'ひていしました', 'hitei shimashita', 'menyangkal'],
                    ['ひざまずいて', 'ひざまずいて', 'hizamazuite', 'berlutut'],
                ]),
            ],
            [
                'title' => 'ルトゥン・カサルン',
                'slug' => 'membaca-jepang-lutung-kasarung-jp',
                'level' => 'N4',
                'summary' => '意地悪な姉に呪われて森に追放された心優しい王女と、彼女を助ける不思議な黒い猿の、西ジャワの伝説。',
                'minutes' => 14,
                'xp' => 30,
                'content' => "昔、西ジャワにパシルバタンという王国があり、プラブ・タパ・アグンという王が治めていました。王には二人の娘がいました。姉のプルバラランと、妹のプルバサリです。王は年をとり、そろそろ王位を譲ろうと考えていました。\n\nこの国の習わしでは、心優しい娘が王位を継ぐことになっていました。王は妹のプルバサリに王位を継がせることに決めました。それを知ったプルバラランは激しく嫉妬し、婚約者のインドラジャヤとともに、妹を追い落とす計画を立てました。\n\nプルバラランは魔女に頼んで、プルバサリの体中に黒いあざができる呪いをかけさせました。そして、「妹は恐ろしい病気にかかった、こんな姿では王にふさわしくない」と国中に言いふらし、プルバサリを森へ追放してしまいました。\n\n森の中で、プルバサリは小さな小屋に一人で暮らし、寂しい毎日を過ごしていました。ある日、ルトゥン・カサルンという名の黒い猿が現れました。この猿は不思議なほど彼女のことを理解しているようで、果物を持ってきたり、危険から守ったりしてくれました。\n\nある夜、ルトゥン・カサルンはプルバサリを森の奥にある不思議な泉へ案内し、そこで水を浴びるように伝えました。言われたとおりにすると、体中のあざはすっかり消え、プルバサリは以前よりもずっと美しくなりました。\n\nプルバサリが美しさを取り戻したという噂は、やがてプルバラランの耳にも届きました。信じられなかったプルバラランは森まで確かめに行きましたが、それでも王位を諦めようとせず、「どちらが王にふさわしいか、いくつかの勝負で決めよう」と提案しました。指の長さや髪の長さの勝負に続き、最後に「婚約者の立派さ」を比べることになりましたが、プルバサリの隣にはルトゥン・カサルンしかいませんでした。\n\nその夜、辺りに不思議な光が満ち、ルトゥン・カサルンの姿は突然ハンサムな王子に変わりました。王子は、自分がグル・ミンダという名で、神々への傲慢な態度のために猿の姿に呪われていたこと、そして心優しい女性の本当の愛によってのみ人間の姿に戻れることを説明しました。\n\n敗れたプルバラランは驚きと恥ずかしさのあまり、自分の過ちを認め、妹に許しを求めました。プルバサリは姉を許し、王子と結婚しました。そして、二人は正しく王位を継ぎ、優しく賢い心でパシルバタン王国を治めました。",
                'translated_content' => "Dahulu kala, di Jawa Barat terdapat sebuah kerajaan bernama Pasir Batang yang diperintah oleh Raja Prabu Tapa Agung. Raja memiliki dua orang putri, yaitu Purbararang sang kakak dan Purbasari sang adik. Karena usianya sudah tua, sang raja mulai berpikir untuk menyerahkan takhtanya.\n\nMenurut adat kerajaan itu, putri yang berhati baiklah yang akan mewarisi takhta. Sang raja pun memutuskan untuk mewariskan takhta kepada Purbasari, sang adik. Mengetahui hal itu, Purbararang menjadi sangat cemburu, dan bersama tunangannya, Indrajaya, ia menyusun rencana untuk menjatuhkan adiknya.\n\nPurbararang meminta seorang penyihir untuk mengutuk tubuh Purbasari agar dipenuhi bintik-bintik hitam. Kemudian ia menyebarkan kabar ke seluruh negeri bahwa adiknya terkena penyakit mengerikan dan tidak pantas menjadi ratu dengan keadaan seperti itu, lalu mengasingkan Purbasari ke hutan.\n\nDi dalam hutan, Purbasari tinggal sendirian di sebuah gubuk kecil, menjalani hari-hari yang sepi. Suatu hari, muncullah seekor lutung hitam bernama Lutung Kasarung. Lutung itu seolah-olah memahami dirinya dengan cara yang aneh, membawakannya buah-buahan, dan melindunginya dari bahaya.\n\nPada suatu malam, Lutung Kasarung membawa Purbasari ke sebuah telaga ajaib di kedalaman hutan dan menyuruhnya berendam di sana. Setelah melakukannya, bintik-bintik hitam di sekujur tubuhnya hilang sepenuhnya, dan Purbasari menjadi jauh lebih cantik dari sebelumnya.\n\nKabar bahwa Purbasari telah kembali cantik akhirnya terdengar oleh Purbararang. Karena tidak percaya, Purbararang pergi ke hutan untuk memastikannya sendiri, tetapi ia tetap tidak mau menyerahkan takhta dan mengusulkan, \"Mari kita tentukan siapa yang pantas menjadi ratu lewat beberapa pertandingan.\" Setelah adu panjang jari dan panjang rambut, terakhir mereka akan membandingkan \"kehebatan tunangan\", tetapi di samping Purbasari hanya ada Lutung Kasarung.\n\nMalam itu, cahaya misterius memenuhi tempat itu, dan sosok Lutung Kasarung tiba-tiba berubah menjadi seorang pangeran tampan. Sang pangeran menjelaskan bahwa namanya adalah Guru Minda, bahwa ia dikutuk menjadi lutung karena sikap sombongnya kepada para dewa, dan bahwa ia hanya bisa kembali ke wujud manusia berkat cinta tulus seorang perempuan berhati baik.\n\nPurbararang yang kalah merasa sangat terkejut dan malu, lalu mengakui kesalahannya dan meminta maaf kepada adiknya. Purbasari pun memaafkan kakaknya, dan menikah dengan sang pangeran. Keduanya kemudian mewarisi takhta dengan sah, dan memerintah Kerajaan Pasir Batang dengan hati yang baik dan bijaksana.",
                'items' => $this->glossary([
                    ['譲ろう', 'ゆずろう', 'yuzurou', 'akan menyerahkan, mewariskan'],
                    ['嫉妬し', 'しっとし', 'shitto shi', 'cemburu'],
                    ['呪いをかけさせました', 'のろいをかけさせました', 'noroi wo kakesasemashita', 'menyuruh mengutuk'],
                    ['言いふらし', 'いいふらし', 'iifurashi', 'menyebarkan gosip'],
                    ['案内し', 'あんないし', 'annai shi', 'memandu, mengantar'],
                    ['取り戻した', 'とりもどした', 'torimodoshita', 'mengembalikan, memulihkan'],
                    ['傲慢な', 'ごうまんな', 'gouman na', 'sombong'],
                ]),
            ],
            [
                'title' => 'クオン・マス',
                'slug' => 'membaca-jepang-keong-mas-jp',
                'level' => 'N3',
                'summary' => '嫉妬深い女によって黄金の巻貝に姿を変えられた王女が、漁師の老婆に助けられ、恋人の王子と再会するという東ジャワの伝説。',
                'minutes' => 15,
                'xp' => 30,
                'content' => "昔、東ジャワにダハという王国があり、そこにはチャンドラ・キラナという美しい王女が住んでいました。彼女は隣国ジェンガラの王子パンジ・アスモロ・バングンと婚約しており、二人は深く愛し合っていました。\n\nところが、宮廷にはデウィ・ガルーという女性がおり、彼女もひそかにパンジ王子に恋をしていました。チャンドラ・キラナへの嫉妬に苦しんだデウィ・ガルーは、ある魔女に助けを求め、恐ろしい呪いをかけてもらうことにしました。\n\n魔女の呪いによって、チャンドラ・キラナはたちまち黄金色に輝く巻貝の姿に変えられてしまいました。そして、その巻貝は川に投げ捨てられ、流れに乗ってどこまでも下流へと運ばれていきました。\n\n川下の村では、貧しい老婆が漁をして生計を立てていました。ある日、老婆が網を引き上げると、見たこともないほど美しい黄金の巻貝がかかっていました。老婆はその不思議な巻貝を持ち帰り、大切な壺に入れて育てることにしました。\n\nそれから毎晩、不思議なことが起こりました。老婆が眠っている間に、巻貝は美しい娘の姿に戻り、こっそりと台所でおいしい料理を作ったり、家の中を掃除したりしていたのです。そして夜が明ける前には、また元の巻貝の姿に戻っていました。\n\n毎朝、誰も作っていないはずの温かい料理が用意されていることを不思議に思った老婆は、ある日わざと出かけるふりをして、こっそりと家の中を見張ることにしました。すると、巻貝から美しい娘が現れたのです。老婆は急いで空になった貝殻を隠し、娘が二度と貝の姿に戻れないようにしました。事情を聞いた老婆は、深く同情し、彼女を実の娘のように大切にかくまうことにしました。\n\n一方、婚約者が突然姿を消してしまったパンジ王子は、深い悲しみに沈んでいました。彼は身分を隠し、旅の芸人のような姿になって国中の村を巡りながら、手がかりを探し続けました。長い旅の末、彼はついにあの老婆の家がある村にたどり着きました。\n\n村で、老婆の家に不思議なほど美しい娘がいるという噂を聞いたパンジ王子は、その家を訪ねてみることにしました。娘の顔を見た瞬間、彼はすぐにチャンドラ・キラナだと気づきました。二人が再会した瞬間、魔女の呪いは完全に解け、デウィ・ガルーの企みも明らかになりました。こうしてパンジ王子とチャンドラ・キラナは共に王宮へ戻り、盛大な結婚式を挙げて、末永く幸せに暮らしました。",
                'translated_content' => "Dahulu kala, di Jawa Timur terdapat sebuah kerajaan bernama Daha, tempat tinggal seorang putri cantik bernama Candra Kirana. Ia bertunangan dengan Pangeran Panji Asmarabangun dari kerajaan tetangga, Jenggala, dan keduanya saling mencintai dengan sangat dalam.\n\nNamun, di istana ada seorang perempuan bernama Dewi Galuh yang diam-diam juga jatuh cinta kepada Pangeran Panji. Karena tersiksa oleh rasa cemburunya terhadap Candra Kirana, Dewi Galuh meminta bantuan seorang penyihir untuk memberikan kutukan yang mengerikan.\n\nAkibat kutukan sang penyihir, Candra Kirana seketika berubah menjadi seekor keong berwarna emas yang berkilauan. Keong itu kemudian dibuang ke sungai, dan hanyut mengikuti arus hingga jauh ke hilir.\n\nDi sebuah desa di hilir sungai, hiduplah seorang nenek miskin yang mencari nafkah dengan menangkap ikan. Suatu hari, ketika nenek itu menarik jaringnya, ia menemukan seekor keong emas yang begitu indah, yang belum pernah ia lihat sebelumnya. Nenek itu membawa pulang keong ajaib itu dan memutuskan untuk memeliharanya di dalam sebuah guci.\n\nSejak saat itu, setiap malam terjadi hal yang aneh. Ketika sang nenek tertidur, keong itu berubah menjadi seorang gadis cantik, lalu diam-diam memasak makanan yang lezat di dapur dan membersihkan seisi rumah. Sebelum fajar tiba, ia kembali berubah menjadi keong seperti semula.\n\nMerasa heran karena setiap pagi selalu ada masakan hangat yang tidak diketahui siapa yang membuatnya, pada suatu hari sang nenek berpura-pura pergi keluar rumah, namun diam-diam ia mengintai dari tempat persembunyian. Ternyata, seorang gadis cantik keluar dari dalam keong itu. Nenek itu segera menyembunyikan cangkang kosongnya agar sang gadis tidak bisa kembali menjadi keong. Setelah mendengar kisahnya, nenek itu merasa sangat iba dan memutuskan untuk melindungi serta merawatnya seperti anak kandungnya sendiri.\n\nSementara itu, Pangeran Panji yang tunangannya tiba-tiba menghilang tenggelam dalam kesedihan yang mendalam. Ia menyamar dengan menyembunyikan jati dirinya, berpenampilan seperti seniman pengembara, dan mengelilingi desa demi desa di seluruh negeri sambil terus mencari petunjuk. Setelah perjalanan panjang, akhirnya ia sampai di desa tempat tinggal nenek itu.\n\nDi desa itu, Pangeran Panji mendengar kabar tentang seorang gadis yang begitu cantik yang tinggal di rumah sang nenek, dan ia pun memutuskan untuk mengunjungi rumah itu. Begitu melihat wajah gadis itu, ia langsung mengenali bahwa itu adalah Candra Kirana. Pada saat mereka bertemu kembali, kutukan sang penyihir pun terhapus sepenuhnya, dan tipu daya Dewi Galuh pun terbongkar. Dengan demikian, Pangeran Panji dan Candra Kirana kembali bersama ke istana, mengadakan pesta pernikahan yang meriah, dan hidup bahagia selamanya.",
                'items' => $this->glossary([
                    ['婚約しており', 'こんやくしており', 'konyaku shiteori', 'bertunangan'],
                    ['嫉妬に苦しんだ', 'しっとにくるしんだ', 'shitto ni kurushinda', 'menderita karena cemburu'],
                    ['投げ捨てられ', 'なげすてられ', 'nagesuterare', 'dibuang'],
                    ['生計を立てて', 'せいけいをたてて', 'seikei wo tatete', 'mencari nafkah'],
                    ['見張る', 'みはる', 'miharu', 'mengawasi, mengintai'],
                    ['かくまう', 'かくまう', 'kakumau', 'menyembunyikan, melindungi'],
                    ['手がかり', 'てがかり', 'tegakari', 'petunjuk'],
                    ['企み', 'たくらみ', 'takurami', 'tipu daya, rencana jahat'],
                ]),
            ],
            [
                'title' => 'ジャカ・タルブと七人の天女',
                'slug' => 'membaca-jepang-jaka-tarub',
                'level' => 'N4',
                'summary' => '天女の羽衣を隠して結婚した若者が、約束を破ったために妻に去られてしまうという中部ジャワの伝説。',
                'minutes' => 13,
                'xp' => 30,
                'content' => "昔、中部ジャワの小さな村に、ジャカ・タルブという若い狩人が住んでいました。ある日、森の中を歩いていると、静かな湖のほうから楽しそうな笑い声が聞こえてきました。近づいてみると、七人の美しい天女たちが湖で水浴びをしていました。天女たちはそれぞれ不思議な羽衣を持っていて、その羽衣のおかげで天と地の間を自由に飛ぶことができるのでした。\n\n天女たちの美しさに心を奪われたジャカ・タルブは、こっそりと一枚の羽衣を隠してしまいました。それは、天女の中で一番若く美しいナワン・ウランのものでした。水浴びを終えた天女たちが天に帰ろうとした時、ナワン・ウランだけは自分の羽衣が見つからず、飛ぶことができませんでした。姉妹たちは仕方なく彼女を残して天へ帰っていきました。\n\n泣いているナワン・ウランに、ジャカ・タルブは知らないふりをして親切に声をかけ、自分の家に泊まるよう勧めました。天へ帰る方法を失ったナワン・ウランは、やがてジャカ・タルブと結婚することになりました。二人は幸せに暮らし、後にナワンシーという娘が生まれました。\n\nナワン・ウランには不思議な力がありました。彼女がご飯を炊く時、たった一粒の米だけでかまどの中がいっぱいのご飯になり、家族全員が十分に食べられるのです。ただし、彼女はジャカ・タルブに一つだけ約束をさせていました。「ご飯を炊いている間は、絶対にかまどの中を見ないでください」。\n\nしかし、ある日、好奇心を抑えられなくなったジャカ・タルブは、ナワン・ウランがご飯を炊いている間に、こっそりとかまどのふたを開けて中をのぞいてしまいました。中にはたった一粒の米しか入っていないのを見て、彼はとても驚きました。その瞬間から不思議な力は消えてしまい、その日からナワン・ウランは普通の女性のように、たくさんの米を使ってご飯を炊かなければならなくなりました。\n\nそのため、米蔵の米はあっという間に少なくなっていきました。ある日、ナワン・ウランが米蔵の奥から米を取り出そうとすると、そこに長い間隠されていた自分の羽衣を見つけました。その瞬間、彼女はすべてを理解しました。羽衣を隠して自分を騙していたのは、ほかでもないジャカ・タルブだったのです。\n\n深く傷ついたナワン・ウランは、ついに天へ帰る時が来たことを知りました。彼女は眠っている娘ナワンシーのそばに行き、最後に優しく語りかけてから、涙を流しながらジャカ・タルブに別れを告げました。「私は天に帰らなければなりません」。そして羽衣をまとうと、彼女は空高く舞い上がり、ジャカ・タルブとナワンシーを地上に残したまま、天へと帰っていきました。",
                'translated_content' => "Dahulu kala, di sebuah desa kecil di Jawa Tengah, hiduplah seorang pemuda pemburu bernama Jaka Tarub. Suatu hari, ketika sedang berjalan di dalam hutan, ia mendengar suara tawa yang riang dari arah sebuah danau yang tenang. Ketika ia mendekat, tampaklah tujuh bidadari cantik yang sedang mandi di danau itu. Setiap bidadari memiliki selendang ajaib, yang berkat kekuatannya mereka dapat terbang bebas antara langit dan bumi.\n\nTerpikat oleh kecantikan para bidadari itu, Jaka Tarub diam-diam menyembunyikan salah satu selendang. Selendang itu adalah milik Nawang Wulan, bidadari yang termuda dan tercantik di antara mereka. Ketika para bidadari selesai mandi dan hendak kembali ke langit, hanya Nawang Wulan yang tidak dapat menemukan selendangnya dan tidak bisa terbang. Saudara-saudarinya pun terpaksa meninggalkannya dan kembali ke langit.\n\nMelihat Nawang Wulan menangis, Jaka Tarub berpura-pura tidak tahu apa yang terjadi dan dengan baik hati menawarkan agar ia tinggal di rumahnya. Karena kehilangan cara untuk kembali ke langit, Nawang Wulan akhirnya menikah dengan Jaka Tarub. Keduanya hidup bahagia, dan kemudian lahirlah seorang putri bernama Nawangsih.\n\nNawang Wulan memiliki kekuatan ajaib. Ketika ia menanak nasi, hanya dengan sebutir beras saja, seluruh dandang menjadi penuh nasi dan cukup untuk seluruh keluarga. Namun, ia meminta satu janji dari Jaka Tarub, \"Selama aku sedang menanak nasi, jangan pernah sekali pun melihat ke dalam dandang.\"\n\nNamun, pada suatu hari, Jaka Tarub tidak dapat menahan rasa penasarannya, dan diam-diam membuka tutup dandang untuk mengintip ke dalamnya saat Nawang Wulan sedang menanak nasi. Ia sangat terkejut melihat di dalamnya hanya ada sebutir beras. Pada saat itu juga, kekuatan ajaib itu lenyap, dan sejak hari itu Nawang Wulan harus menanak nasi dengan banyak beras seperti perempuan biasa.\n\nAkibatnya, persediaan beras di lumbung dengan cepat berkurang. Pada suatu hari, ketika Nawang Wulan hendak mengambil beras dari bagian dalam lumbung, ia menemukan selendangnya sendiri yang telah lama disembunyikan di sana. Pada saat itu, ia memahami semuanya. Orang yang menyembunyikan selendangnya dan menipunya selama ini tidak lain adalah Jaka Tarub.\n\nDengan hati yang terluka dalam, Nawang Wulan akhirnya menyadari bahwa saatnya untuk kembali ke langit telah tiba. Ia mendekati putrinya, Nawangsih, yang sedang tidur, membisikkan kata-kata lembut untuk terakhir kalinya, lalu sambil menitikkan air mata ia berpamitan kepada Jaka Tarub. \"Aku harus kembali ke langit.\" Setelah mengenakan selendangnya, ia pun terbang tinggi ke angkasa, meninggalkan Jaka Tarub dan Nawangsih di bumi, lalu kembali ke langit.",
                'items' => $this->glossary([
                    ['水浴びをして', 'みずあびをして', 'mizuabi wo shite', 'mandi'],
                    ['心を奪われた', 'こころをうばわれた', 'kokoro wo ubawareta', 'terpikat hatinya'],
                    ['仕方なく', 'しかたなく', 'shikatanaku', 'terpaksa'],
                    ['好奇心', 'こうきしん', 'koukishin', 'rasa penasaran'],
                    ['のぞいて', 'のぞいて', 'nozoite', 'mengintip'],
                    ['傷ついた', 'きずついた', 'kizutsuita', 'terluka hatinya'],
                    ['舞い上がり', 'まいあがり', 'maiagari', 'terbang naik'],
                ]),
            ],
            [
                'title' => 'チンデラス',
                'slug' => 'membaca-jepang-cindelaras-jp',
                'level' => 'N5',
                'summary' => '森で育てた不思議な鶏のおかげで、本当の父である王と再会できた少年の東ジャワの伝説。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔、ラデン・プトラという王様がいました。王様には、正妻と側室がいました。側室は正妻のことをねたんでいて、王様に「正妻があなたを毒殺しようとしています」と嘘をつきました。\n\n王様はよく確かめないでその嘘を信じ、とても怒りました。そして、正妻はお腹に赤ちゃんがいたのに、森へ追い出されてしまいました。\n\n森の中で、正妻は男の子を産み、チンデラスと名付けました。二人は小さな小屋で仲良く暮らし、時々、親切な仙人が二人を助けてくれました。\n\nチンデラスは元気な少年に育ちました。ある日、野鳥が彼のそばに卵を一つ落としていきました。チンデラスがその卵を大切に温めると、やがて一羽の雄鶏が生まれました。\n\nその雄鶏は強く育ち、不思議な美しい声で鳴きました。その鳴き声はまるで言葉のように聞こえました。「コケコッコー、僕の主人はチンデラス、主人の父はラデン・プトラ王」。この不思議な鳴き声を聞いた人々は驚き、王様にこのことを伝えました。\n\n興味を持ったラデン・プトラ王は、チンデラスを城へ招き、鶏合わせの勝負をすることにしました。チンデラスの雄鶏は、王様のどの鶏にも簡単に勝ちました。王様はチンデラスに今までの生活について尋ね、チンデラスは森で暮らす母のことを話しました。\n\n話を聞いたラデン・プトラ王は、自分の間違いに気づきました。チンデラスは本当の息子であり、正妻には何の罪もなかったのです。王様は正妻とチンデラスを城に呼び戻し、嘘をついた側室を罰しました。こうして家族は再び一緒に、幸せに暮らしました。",
                'translated_content' => "Dahulu kala, ada seorang raja bernama Raden Putra. Sang raja memiliki seorang permaisuri dan seorang selir. Sang selir merasa iri kepada permaisuri, dan berbohong kepada raja, \"Permaisuri sedang berencana meracuni Anda.\"\n\nRaja mempercayai kebohongan itu tanpa memeriksanya terlebih dahulu, dan menjadi sangat marah. Lalu, meskipun permaisuri sedang mengandung, ia diusir ke dalam hutan.\n\nDi dalam hutan, sang permaisuri melahirkan seorang anak laki-laki dan menamainya Cindelaras. Keduanya hidup rukun di sebuah gubuk kecil, dan sesekali seorang pertapa yang baik hati membantu mereka.\n\nCindelaras tumbuh menjadi anak laki-laki yang sehat. Suatu hari, seekor burung liar menjatuhkan sebutir telur di dekatnya. Setelah Cindelaras menghangatkan telur itu dengan penuh perhatian, lahirlah seekor ayam jantan.\n\nAyam jantan itu tumbuh kuat dan berkokok dengan suara yang indah dan ajaib. Kokoknya terdengar seperti kata-kata, \"Kukuruyuk, tuanku adalah Cindelaras, ayah tuanku adalah Raja Raden Putra.\" Orang-orang yang mendengar kokok ajaib itu sangat terkejut dan menyampaikan hal ini kepada sang raja.\n\nRaja Raden Putra yang tertarik lalu mengundang Cindelaras ke istana untuk mengadakan pertandingan sabung ayam. Ayam jantan milik Cindelaras dengan mudah mengalahkan semua ayam milik sang raja. Raja pun bertanya kepada Cindelaras tentang kehidupannya selama ini, dan Cindelaras menceritakan tentang ibunya yang tinggal di hutan.\n\nSetelah mendengar cerita itu, Raja Raden Putra menyadari kesalahannya. Cindelaras adalah anak kandungnya yang sesungguhnya, dan sang permaisuri sama sekali tidak bersalah. Raja pun memanggil kembali permaisuri dan Cindelaras ke istana, dan menghukum selir yang telah berbohong. Dengan demikian, keluarga itu kembali hidup bersama dengan bahagia.",
                'items' => $this->glossary([
                    ['側室', 'そくしつ', 'sokushitsu', 'selir'],
                    ['ねたんでいて', 'ねたんでいて', 'netande ite', 'iri hati'],
                    ['嘘をつきました', 'うそをつきました', 'uso wo tsukimashita', 'berbohong'],
                    ['追い出されて', 'おいだされて', 'oidasarete', 'diusir'],
                    ['温める', 'あたためる', 'atatameru', 'menghangatkan'],
                    ['招き', 'まねき', 'maneki', 'mengundang'],
                    ['罰しました', 'ばっしました', 'basshimashita', 'menghukum'],
                ]),
            ],
            [
                'title' => 'バニュワンギの起源',
                'slug' => 'membaca-jepang-asal-usul-banyuwangi',
                'level' => 'N4',
                'summary' => '無実の罪で妻を川に流してしまった貴族の後悔から、川の水が香るようになったという東ジャワの伝説。',
                'minutes' => 13,
                'xp' => 30,
                'content' => "昔、東ジャワのある地域に、ラデン・バンテランという貴族が住んでいました。彼にはスリ・タンジュンという美しく貞淑な妻がいて、二人は幸せな結婚生活を送っていました。\n\nある日、バンテランは仕事のために遠くへ出かけなければなりませんでした。彼が留守の間、以前からスリ・タンジュンに恋心を抱いていた一人の男が彼女に近づき、夫と別れて自分と一緒になるよう誘いました。しかし、スリ・タンジュンはきっぱりとその誘いを断り、夫への貞節を守り通しました。\n\n誘いを断られて恨みを抱いたその男は、バンテランのもとへ行き、「あなたが留守の間、スリ・タンジュンは別の男と浮気をしていました」と嘘の話をしました。\n\n家に帰ったバンテランは、その話を信じ込み、激しい怒りに我を忘れてしまいました。彼は妻の言い訳に耳を貸そうともせず、彼女を川岸まで連れて行き、厳しく罰しようとしました。\n\n涙を流しながら、スリ・タンジュンは自分の潔白を訴えました。「もし私が本当に不貞を働いていたなら、この川の水は悪臭を放つでしょう。でも、私が無実ならば、水は良い香りを放つはずです」。そう言い終えると、彼女は川に突き落とされてしまいました。\n\nスリ・タンジュンは川の流れに飲み込まれ、命を落としてしまいました。すると、その瞬間から、川の水はすばらしい香りを放ち始め、その香りはあたり一帯に広がっていきました。\n\n突然香り出した川に、村人たちは驚きました。やがてバンテランは、あの男が語ったことがすべて嘘だったと知ることになりました。無実の、心優しい妻を自らの手で殺してしまったことに気づいた彼は、深い後悔に包まれました。\n\nこの悲しい出来事と、スリ・タンジュンの潔白を証明した香り高い川にちなんで、この地域は「バニュワンギ」と呼ばれるようになりました。「バニュ」は水、「ワンギ」は香りという意味です。この伝説は、今も東ジャワで語り継がれています。",
                'translated_content' => "Dahulu kala, di suatu daerah di Jawa Timur, hiduplah seorang bangsawan bernama Raden Banterang. Ia memiliki seorang istri yang cantik dan setia bernama Sri Tanjung, dan keduanya menjalani kehidupan pernikahan yang bahagia.\n\nPada suatu hari, Banterang harus pergi jauh untuk suatu urusan. Selama kepergiannya, seorang laki-laki yang sejak lama memendam perasaan cinta kepada Sri Tanjung mendekatinya dan mengajaknya untuk meninggalkan suaminya dan bersama dengannya. Namun, Sri Tanjung dengan tegas menolak ajakan itu dan tetap menjaga kesetiaannya kepada suaminya.\n\nKarena ditolak, laki-laki itu menyimpan dendam, lalu pergi menemui Banterang dan berbohong, \"Selama Anda pergi, Sri Tanjung telah berselingkuh dengan pria lain.\"\n\nSesampainya di rumah, Banterang mempercayai cerita itu sepenuhnya dan menjadi sangat marah hingga lupa diri. Tanpa mau mendengarkan penjelasan istrinya, ia membawanya ke tepi sungai dengan maksud menghukumnya dengan keras.\n\nSambil menangis, Sri Tanjung menyatakan kesuciannya, \"Jika aku benar-benar telah berbuat tidak setia, biarlah air sungai ini mengeluarkan bau busuk. Namun, jika aku tidak bersalah, biarlah air ini mengeluarkan wangi yang harum.\" Setelah mengucapkan hal itu, ia pun didorong jatuh ke dalam sungai.\n\nSri Tanjung terseret oleh arus sungai dan kehilangan nyawanya. Pada saat itu juga, air sungai mulai mengeluarkan wangi yang luar biasa harum, dan aroma itu menyebar ke seluruh daerah sekitarnya.\n\nWarga desa terkejut melihat sungai yang tiba-tiba menjadi harum itu. Tak lama kemudian, Banterang mengetahui bahwa semua yang dikatakan pria itu adalah kebohongan belaka. Menyadari bahwa ia telah membunuh istrinya sendiri yang tidak bersalah dan berhati baik, ia pun diliputi penyesalan yang mendalam.\n\nUntuk mengenang peristiwa yang menyedihkan ini, serta sungai yang harum yang membuktikan kesucian Sri Tanjung, daerah ini kemudian dinamai \"Banyuwangi\". \"Banyu\" berarti air, dan \"wangi\" berarti harum. Legenda ini masih terus diwariskan hingga sekarang di Jawa Timur.",
                'items' => $this->glossary([
                    ['貞淑な', 'ていしゅくな', 'teishuku na', 'setia, berbudi'],
                    ['恋心を抱いて', 'こいごころをいだいて', 'koigokoro wo idaite', 'memendam perasaan cinta'],
                    ['断り', 'ことわり', 'kotowari', 'menolak'],
                    ['恨みを抱いた', 'うらみをいだいた', 'urami wo idaita', 'menyimpan dendam'],
                    ['信じ込み', 'しんじこみ', 'shinjikomi', 'mempercayai sepenuhnya'],
                    ['潔白', 'けっぱく', 'keppaku', 'tidak bersalah, kesucian'],
                    ['突き落とされて', 'つきおとされて', 'tsukiotosarete', 'didorong jatuh'],
                ]),
            ],

            [
                'title' => 'ラワ・プニンの伝説',
                'slug' => 'membaca-jepang-rawa-pening',
                'level' => 'N4',
                'summary' => '貧しい老女に親切にされなかった村が洪水で湖に変わる、中部ジャワの伝説。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔、中部ジャワのある村に、貧しいおばあさんが一人で暮らしていました。ある日、森の中で不思議な卵を見つけ、大切に持ち帰りました。その卵から生まれたのは、人間の男の子ではなく、一匹の小さな蛇でした。おばあさんは驚きましたが、その蛇を我が子のようにかわいがり、バル・クリンティンと名付けました。\n\nバル・クリンティンはすくすくと育ち、やがて大きな蛇になりました。ある日、彼は母に「僕のお父さんは誰ですか」と尋ねました。おばあさんは、彼の父親は山の向こうに住む力のある人だと教えました。バル・クリンティンは父に会うため、一人で長い旅に出ることにしました。\n\n何日も歩き続けて、バル・クリンティンはようやく一つの村に着きました。しかし、村人たちは大きな蛇の姿を見て恐れ、「化け物が来た」と叫んで彼を追い払おうとしました。バル・クリンティンは何度も「僕は悪いことをしません。休ませてください」と頼みましたが、誰も彼の話を聞いてくれませんでした。石を投げる人までいました。\n\n村の隅に、貧しい一人暮らしのおばあさんが住んでいました。彼女だけはバル・クリンティンを怖がらず、家に招き入れて食べ物を分けてくれました。バル・クリンティンはそのやさしさに深く感謝しました。\n\n村人たちのひどい態度に怒ったバル・クリンティンは、皆に一つの勝負を持ちかけました。「地面に刺さったこの串を、力のある人は抜いてみてください」。村の若者たちは次々に挑戦しましたが、串はびくとも動きませんでした。最後にバル・クリンティン自身が串を引き抜くと、その穴からは水が止まらずに湧き出し始めました。\n\n串を抜く前、バル・クリンティンはあのやさしいおばあさんにそっと伝えていました。「もうすぐこの村は水に沈みます。臼をひっくり返して、その上に乗って逃げてください」。おばあさんは言われた通りに臼を用意し、村を離れました。\n\n穴から湧き出た水はどんどん増え、あっという間に村全体を飲み込んでいきました。村人たちを笑い、いじめた人々は水の中に消え、村は大きな湖に変わってしまいました。この湖が、今も中部ジャワに残るラワ・プニンです。\n\nおばあさんだけは臼に乗って波の上を漂い、無事に助かりました。この物語は、人に親切にすることの大切さと、他人を見た目で判断していじめることの恐ろしさを、今も私たちに伝えています。",
                'translated_content' => "Dahulu kala, di sebuah desa di Jawa Tengah, hiduplah seorang nenek miskin yang tinggal sendirian. Suatu hari, ia menemukan sebutir telur ajaib di dalam hutan dan membawanya pulang dengan hati-hati. Dari telur itu lahir bukan seorang anak manusia, melainkan seekor ular kecil. Nenek itu terkejut, tetapi ia menyayangi ular itu seperti anaknya sendiri dan menamainya Baru Klinthing.\n\nBaru Klinthing tumbuh dengan cepat dan akhirnya menjadi seekor ular besar. Suatu hari, ia bertanya kepada ibunya, \"Siapakah ayahku?\" Nenek itu memberitahunya bahwa ayahnya adalah seorang yang berkuasa yang tinggal di balik gunung. Baru Klinthing pun memutuskan untuk pergi sendirian dalam perjalanan panjang untuk bertemu ayahnya.\n\nSetelah berjalan berhari-hari, Baru Klinthing akhirnya tiba di sebuah desa. Namun, warga desa ketakutan melihat sosok ular besar itu dan berteriak, \"Monster datang!\" sambil mencoba mengusirnya. Baru Klinthing berulang kali memohon, \"Saya tidak akan berbuat jahat. Tolong izinkan saya beristirahat,\" tetapi tidak ada yang mau mendengarkannya. Bahkan ada yang melemparinya dengan batu.\n\nDi sudut desa itu, tinggal seorang nenek miskin yang hidup sebatang kara. Hanya dialah yang tidak takut kepada Baru Klinthing; ia mengajaknya masuk ke rumah dan membagikan makanan untuknya. Baru Klinthing sangat berterima kasih atas kebaikan hatinya.\n\nMarah atas perlakuan buruk warga desa, Baru Klinthing mengajukan sebuah tantangan kepada mereka semua. \"Cobalah cabut tusuk yang tertancap di tanah ini, bagi siapa saja yang merasa kuat.\" Para pemuda desa mencoba satu demi satu, tetapi tusuk itu sama sekali tidak bergerak. Akhirnya, Baru Klinthing sendiri yang mencabut tusuk itu, dan dari lubangnya air pun menyembur tanpa henti.\n\nSebelum mencabut tusuk itu, Baru Klinthing diam-diam berpesan kepada nenek baik hati itu, \"Sebentar lagi desa ini akan tenggelam. Baliklah lesung ini dan naiklah di atasnya untuk menyelamatkan diri.\" Nenek itu pun menyiapkan lesung sesuai pesannya dan meninggalkan desa.\n\nAir yang menyembur dari lubang itu terus bertambah banyak dan dalam sekejap menenggelamkan seluruh desa. Orang-orang yang telah menertawakan dan mengejek Baru Klinthing lenyap ditelan air, dan desa itu pun berubah menjadi sebuah danau besar. Danau inilah yang hingga kini dikenal sebagai Rawa Pening di Jawa Tengah.\n\nHanya nenek itu yang selamat, mengapung di atas lesungnya di atas gelombang air. Kisah ini, hingga sekarang, mengajarkan kita pentingnya bersikap baik kepada sesama serta bahaya menghina orang lain hanya karena penampilannya.",
                'items' => $this->glossary([
                    ['蛇', 'へび', 'hebi', 'ular'],
                    ['追い払おう', 'おいはらおう', 'oiharaou', 'mengusir (bentuk niat)'],
                    ['串', 'くし', 'kushi', 'tusuk/sujen'],
                    ['湧き出し', 'わきだし', 'wakidashi', 'menyembur keluar'],
                    ['臼', 'うす', 'usu', 'lesung/lumpang batu'],
                    ['飲み込んで', 'のみこんで', 'nomikonde', 'menelan (bentuk te)'],
                    ['漂い', 'ただよい', 'tadayoi', 'mengapung'],
                ]),
            ],
            [
                'title' => 'ニ・ロロ・キドゥル、南海の女王',
                'slug' => 'membaca-jepang-nyi-roro-kidul',
                'level' => 'N3',
                'summary' => '呪いをかけられた王女が南の海で美しさと力を取り戻す、西ジャワの伝説。',
                'minutes' => 13,
                'xp' => 30,
                'content' => "昔、西ジャワにあったパジャジャラン王国に、カディタという美しい王女がいました。彼女は心優しく、聡明で、多くの人々に愛されていましたが、それゆえに王妃の座をねらう別の妃から激しく妬まれていました。\n\nその妃は黒魔術に精通しており、ひそかに呪術師に頼んでカディタ王女に呪いをかけさせました。ある朝、王女が目を覚ますと、全身の肌に恐ろしい皮膚病が広がっており、美しかった姿は見る影もなくなっていました。\n\n王宮では、王女の醜い姿を恐れたり気味悪がったりする声が広がり、ついに王は家臣たちの強い勧めに逆らえず、涙をのんでカディタを王宮から追放してしまいました。王女は一夜にして、すべてを失ったのです。\n\n行く当てもなく、カディタはひとり森や山を彷徨い歩きました。皮膚病に苦しみながらも、誰にも頼ることができず、彼女はただ南の方角を目指して歩き続けました。\n\n長い旅の末、カディタはついに南の海岸にたどり着きました。疲れ果てて岩に座り込んだとき、どこからともなく神秘的な声が聞こえてきました。「その海に体を浸しなさい。そうすればお前は救われるだろう」。\n\n半信半疑ながらも、カディタは声に従って荒々しい南の海に身を投じました。すると不思議なことに、彼女の肌を覆っていた病は跡形もなく消え去り、代わりに、以前にも増して輝くばかりの美しさが彼女に宿りました。\n\n海から上がったカディタは、もはや人間ではなく、超自然的な力を持つ存在へと生まれ変わっていました。彼女はその日から「ニ・ロロ・キドゥル」と呼ばれ、南の海を統べる霊的な女王として、永遠の美しさと力を手にしたのです。\n\nそれ以来、ジャワの人々はニ・ロロ・キドゥルを南海の守護者として敬い、南の海に入るときは緑色の服を避けるという言い伝えが今も語り継がれています。",
                'translated_content' => "Dahulu kala, di Kerajaan Pajajaran yang terletak di Jawa Barat, hiduplah seorang putri cantik bernama Kadita. Ia berhati baik dan cerdas, serta dicintai oleh banyak orang, tetapi justru karena itulah ia sangat dibenci oleh seorang selir lain yang mengincar kedudukan sebagai permaisuri.\n\nSelir itu mahir dalam ilmu hitam, dan diam-diam meminta seorang dukun untuk mengutuk Putri Kadita. Suatu pagi, ketika sang putri terbangun, seluruh kulitnya telah dipenuhi penyakit kulit yang mengerikan, dan kecantikannya yang dahulu tak lagi tersisa.\n\nDi istana, muncul suara-suara yang takut dan jijik melihat rupa buruk sang putri, dan akhirnya raja pun tidak dapat menolak desakan keras para pejabat istana. Dengan berat hati, ia mengusir Kadita dari istana. Dalam semalam, sang putri kehilangan segalanya.\n\nTanpa tujuan, Kadita mengembara sendirian melewati hutan dan gunung. Meski menderita karena penyakit kulitnya, ia tidak bisa bergantung pada siapa pun, dan hanya terus berjalan menuju arah selatan.\n\nSetelah perjalanan panjang, Kadita akhirnya tiba di pantai selatan. Ketika ia duduk kelelahan di atas batu karang, entah dari mana terdengar sebuah suara misterius, \"Rendamlah tubuhmu di laut itu. Maka engkau akan diselamatkan.\"\n\nMeski setengah percaya setengah ragu, Kadita menuruti suara itu dan menerjunkan diri ke laut selatan yang ganas. Anehnya, penyakit yang menutupi kulitnya lenyap tanpa bekas, dan sebagai gantinya, kecantikan yang bahkan lebih bercahaya dari sebelumnya menyelimuti dirinya.\n\nSetelah keluar dari laut, Kadita bukan lagi manusia biasa, melainkan telah berubah menjadi sosok berkekuatan gaib. Sejak hari itu, ia dipanggil \"Nyi Roro Kidul\", dan sebagai ratu spiritual yang menguasai laut selatan, ia memperoleh kecantikan dan kekuatan abadi.\n\nSejak saat itu, masyarakat Jawa menghormati Nyi Roro Kidul sebagai pelindung laut selatan, dan hingga kini masih diwariskan kepercayaan untuk menghindari pakaian berwarna hijau ketika memasuki laut selatan.",
                'items' => $this->glossary([
                    ['妬まれて', 'ねたまれて', 'netamarete', 'dibenci/didengki (bentuk pasif-te)'],
                    ['呪い', 'のろい', 'noroi', 'kutukan'],
                    ['追放して', 'ついほうして', 'tsuihoushite', 'mengusir/membuang (bentuk te)'],
                    ['彷徨い', 'さまよい', 'samayoi', 'mengembara'],
                    ['身を投じました', 'みをとうじました', 'mi wo toujimashita', 'menerjunkan diri'],
                    ['生まれ変わって', 'うまれかわって', 'umarekawatte', 'terlahir kembali (bentuk te)'],
                    ['統べる', 'すべる', 'suberu', 'memerintah/menguasai'],
                ]),
            ],
            [
                'title' => 'シトゥ・バゲンディ',
                'slug' => 'membaca-jepang-situ-bagendit',
                'level' => 'N5',
                'summary' => 'けちな金持ちの女が神秘的な物乞いの怒りを買い、その屋敷が湖に沈む、西ジャワの伝説。',
                'minutes' => 10,
                'xp' => 30,
                'content' => "西ジャワのある村に、ニ・エンディットという女の人が住んでいました。彼女はとてもお金持ちでしたが、とてもけちでした。\n\n村には貧しい人がたくさんいました。困っている人がお金や食べ物を借りに来ても、ニ・エンディットはいつも断りました。「わたしのものは、わたしのものです」と彼女はいつも言いました。\n\nある日、村でお祭りがありました。そこに、汚い服を着たおじいさんの物乞いが来ました。おじいさんは「お腹がすきました。何か食べる物をください」と頼みました。しかし、ニ・エンディットは笑って、おじいさんを追い返しました。\n\n実は、そのおじいさんは特別な力を持っていました。おじいさんは怒って、地面に木の棒を刺しました。そして村人に言いました。「この棒を抜けるか、やってみなさい」。\n\n強い男の人たちが何人も棒を抜こうとしましたが、誰も抜けませんでした。最後に、貧しい孤児の男の子が棒に触ると、棒は簡単に地面から抜けました。\n\nすると、穴から水がどんどん出てきました。水は止まらず、村中に広がりました。ニ・エンディットの家も、お金も、全部水の中に沈んでしまいました。\n\nその水は大きな湖になりました。今、この湖はシトゥ・バゲンディと呼ばれています。人々は今も、けちで意地悪だったニ・エンディットの話を覚えています。",
                'translated_content' => "Di sebuah desa di Jawa Barat, hiduplah seorang perempuan bernama Nyi Endit. Ia sangat kaya, tetapi sangat pelit.\n\nDi desa itu banyak orang miskin. Ketika orang-orang yang kesusahan datang untuk meminjam uang atau makanan, Nyi Endit selalu menolak. \"Milikku adalah milikku,\" katanya selalu.\n\nSuatu hari, ada perayaan di desa itu. Datanglah seorang kakek pengemis berpakaian kotor. Kakek itu meminta, \"Perutku lapar. Tolong berikan aku makanan.\" Namun, Nyi Endit tertawa dan mengusir kakek itu pergi.\n\nSebenarnya, kakek itu memiliki kekuatan istimewa. Kakek itu marah, lalu menancapkan sebatang tongkat kayu ke tanah. Ia berkata kepada warga desa, \"Cobalah cabut tongkat ini kalau bisa.\"\n\nBanyak pria kuat mencoba mencabut tongkat itu, tetapi tidak ada yang berhasil. Akhirnya, seorang anak laki-laki yatim piatu yang miskin menyentuh tongkat itu, dan tongkat itu pun tercabut dengan mudah dari tanah.\n\nKemudian, air keluar deras dari lubang itu. Air itu tidak berhenti dan menyebar ke seluruh desa. Rumah Nyi Endit dan semua hartanya pun tenggelam ke dalam air.\n\nAir itu berubah menjadi sebuah danau besar. Kini, danau ini disebut Situ Bagendit. Orang-orang hingga sekarang masih mengingat kisah Nyi Endit yang pelit dan jahat.",
                'items' => $this->glossary([
                    ['けち', 'けち', 'kechi', 'pelit'],
                    ['断りました', 'ことわりました', 'kotowarimashita', 'menolak (bentuk lampau)'],
                    ['物乞い', 'ものごい', 'monogoi', 'pengemis'],
                    ['追い返しました', 'おいかえしました', 'oikaeshimashita', 'mengusir pergi (bentuk lampau)'],
                    ['孤児', 'こじ', 'koji', 'anak yatim piatu'],
                    ['沈んで', 'しずんで', 'shizunde', 'tenggelam (bentuk te)'],
                ]),
            ],
            [
                'title' => 'スラバヤの起源、スラとバヤの伝説',
                'slug' => 'membaca-jepang-sura-dan-baya',
                'level' => 'N5',
                'summary' => 'サメとワニが縄張り争いの末に激しく戦い、その地にスラバヤの町ができたという東ジャワの伝説。',
                'minutes' => 10,
                'xp' => 30,
                'content' => "昔、東ジャワの海に、サメのスラと、ワニのバヤが住んでいました。二匹ともとても強く、いつも獲物を取り合って戦っていました。\n\n海でも川でも、二匹はよく戦いました。町の動物たちは、二匹の戦いをとても怖がっていました。ある日、スラとバヤは話し合うことにしました。\n\n「もう戦うのはやめよう」とスラが言いました。「海はわたしの場所、川と陸はお前の場所にしよう。川の入り口を境にしよう」。バヤは賛成しました。\n\nしばらくの間、二匹は約束を守りました。しかし、ある日、スラはお腹がすいて、こっそり川に入って魚を食べました。\n\nバヤはそれを見て、とても怒りました。「お前は約束を破った!」とバヤは叫びました。スラは「わたしは間違えただけだ」と言いましたが、バヤは信じませんでした。\n\n二匹は川の入り口で、大きな戦いを始めました。二匹とも強い力で噛み合い、長い間戦い続けました。とうとう、二匹は傷だらけになって離れていきました。\n\nこの戦いが起きた場所に、後で町ができました。人々はスラとバヤの名前から、その町を「スラバヤ」と呼ぶようになりました。今も、スラバヤの町にはサメとワニの像があります。",
                'translated_content' => "Dahulu kala, di laut Jawa Timur, hiduplah seekor ikan hiu bernama Sura dan seekor buaya bernama Baya. Keduanya sangat kuat, dan selalu bertarung memperebutkan mangsa.\n\nBaik di laut maupun di sungai, keduanya sering bertengkar. Hewan-hewan di sekitar sangat takut melihat pertarungan mereka berdua. Suatu hari, Sura dan Baya memutuskan untuk berunding.\n\n\"Ayo kita berhenti bertarung,\" kata Sura. \"Laut menjadi wilayahku, sungai dan darat menjadi wilayahmu. Mari kita jadikan muara sungai sebagai batasnya.\" Baya pun setuju.\n\nUntuk beberapa waktu, keduanya menepati janji itu. Namun, suatu hari, Sura merasa lapar dan diam-diam masuk ke sungai untuk memakan ikan.\n\nBaya melihat hal itu dan menjadi sangat marah. \"Kau telah melanggar janji!\" teriak Baya. Sura berkata, \"Aku hanya salah masuk,\" tetapi Baya tidak percaya.\n\nKeduanya memulai pertarungan besar di muara sungai. Mereka saling menggigit dengan kekuatan penuh dan terus bertarung dalam waktu lama. Akhirnya, keduanya berpisah dengan tubuh penuh luka.\n\nDi tempat pertarungan itu terjadi, kemudian berdirilah sebuah kota. Orang-orang menamai kota itu \"Surabaya\", diambil dari nama Sura dan Baya. Hingga kini, di kota Surabaya masih terdapat patung ikan hiu dan buaya.",
                'items' => $this->glossary([
                    ['獲物', 'えもの', 'emono', 'mangsa/buruan'],
                    ['境にしよう', 'さかいにしよう', 'sakai ni shiyou', 'jadikan sebagai batas'],
                    ['約束を守りました', 'やくそくをまもりました', 'yakusoku wo mamorimashita', 'menepati janji'],
                    ['破った', 'やぶった', 'yabutta', 'melanggar (bentuk lampau)'],
                    ['噛み合い', 'かみあい', 'kamiai', 'saling menggigit'],
                    ['傷だらけ', 'きずだらけ', 'kizudarake', 'penuh luka'],
                ]),
            ],
            [
                'title' => 'テラガ・ワルナ、色の湖',
                'slug' => 'membaca-jepang-telaga-warna',
                'level' => 'N4',
                'summary' => 'わがままな王女が村人の贈り物を粗末にし、涙と宝石から色とりどりの湖ができる、西ジャワの伝説。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔、西ジャワにある王国に、王様とお后様が住んでいました。二人には長い間子どもがいなかったので、毎日神様に子どもを授けてくださいとお祈りしていました。\n\n長い年月が経って、ついに美しい女の子が生まれました。王様とお后様はとても喜び、その子にギラン・ルクミニという名前をつけました。二人は彼女をとても大切に育て、欲しい物は何でも与えました。\n\nしかし、王女は大人になるにつれて、わがままで思いやりのない性格になってしまいました。それでも王様とお后様は、娘をとても愛していました。\n\n王女の誕生日が近づくと、王国中の人々が喜んでお祝いの準備をしました。村人たちは、自分の少ない宝石を持ち寄って、心を込めて美しい首飾りを作りました。\n\n誕生日の日、王様とお后様は、その首飾りを王女に贈りました。「これは村人たちが心を込めて作った贈り物ですよ」とお后様は言いました。\n\nところが、王女はその首飾りを見て、「こんな安っぽい物、いりません」と言い、地面に投げ捨ててしまいました。お后様は恥ずかしさと悲しさのあまり、思わず王女の頬を叩いてしまいました。\n\n王女は激しく泣き出し、涙が止まりませんでした。彼女の涙はどんどん流れ続け、地面に散らばった宝石と混ざり合って、大きな水たまりになっていきました。\n\nその水たまりは、やがて美しい湖になりました。宝石の色が混ざり合っているため、この湖は光の加減で色々な色に輝きます。人々はこの湖を「テラガ・ワルナ」、色の湖と呼ぶようになりました。",
                'translated_content' => "Dahulu kala, di sebuah kerajaan di Jawa Barat, hiduplah seorang raja dan permaisuri. Selama bertahun-tahun mereka tidak memiliki anak, sehingga setiap hari mereka berdoa kepada Tuhan agar dikaruniai seorang anak.\n\nSetelah bertahun-tahun berlalu, akhirnya lahirlah seorang putri yang cantik. Raja dan permaisuri sangat bergembira dan menamainya Gilang Rukmini. Mereka membesarkannya dengan sangat memanjakan, memberikan apa pun yang diinginkannya.\n\nNamun, seiring bertambah dewasa, sang putri tumbuh menjadi pribadi yang manja dan tidak memiliki rasa peduli terhadap orang lain. Meski begitu, raja dan permaisuri tetap sangat menyayangi putri mereka.\n\nKetika hari ulang tahun sang putri semakin dekat, seluruh rakyat kerajaan dengan senang hati mempersiapkan perayaan. Para warga desa mengumpulkan perhiasan mereka yang sedikit, lalu dengan sepenuh hati menganyam sebuah kalung yang indah.\n\nPada hari ulang tahunnya, raja dan permaisuri menghadiahkan kalung itu kepada sang putri. \"Ini adalah hadiah yang dibuat oleh rakyat dengan sepenuh hati,\" kata permaisuri.\n\nNamun, sang putri memandang kalung itu dan berkata, \"Aku tidak mau barang murahan seperti ini,\" lalu melemparkannya ke tanah. Permaisuri, karena malu dan sedih yang teramat sangat, tanpa sadar menampar pipi putrinya.\n\nSang putri menangis dengan keras dan air matanya tak berhenti mengalir. Air matanya terus mengalir dan bercampur dengan perhiasan yang berserakan di tanah, membentuk genangan air yang semakin besar.\n\nGenangan air itu lambat laun berubah menjadi sebuah danau yang indah. Karena warna-warna perhiasan yang bercampur di dalamnya, danau ini berkilau dengan berbagai warna tergantung pada cahaya. Orang-orang pun menyebut danau ini \"Telaga Warna\", danau berwarna-warni.",
                'items' => $this->glossary([
                    ['授けて', 'さずけて', 'sazukete', 'menganugerahkan (bentuk te)'],
                    ['わがまま', 'わがまま', 'wagamama', 'manja/egois'],
                    ['持ち寄って', 'もちよって', 'mochiyotte', 'membawa berkumpul (bentuk te)'],
                    ['安っぽい', 'やすっぽい', 'yasuppoi', 'murahan'],
                    ['投げ捨てて', 'なげすてて', 'nagesutete', 'membuang (bentuk te)'],
                    ['叩いて', 'たたいて', 'tataite', 'memukul/menampar (bentuk te)'],
                    ['散らばった', 'ちらばった', 'chirabatta', 'berserakan (bentuk lampau)'],
                ]),
            ],
            [
                'title' => 'カンチルとワニ',
                'slug' => 'membaca-jepang-kancil-dan-buaya',
                'level' => 'N5',
                'summary' => '賢いカンチルがワニたちを騙して川を渡る、ヌサンタラの動物寓話。',
                'minutes' => 10,
                'xp' => 30,
                'content' => "森の近くに、大きな川がありました。川の向こうには、おいしい果物がたくさんある果樹園がありました。カンチルという小さな鹿は、その果物を食べたいと思いました。\n\nしかし、川にはたくさんのワニが住んでいました。ワニたちはいつもカンチルを食べようと待っていました。カンチルはどうやって川を渡ろうか、一生懸命考えました。\n\nカンチルは良い考えを思いつきました。カンチルはワニたちに大きな声で言いました。「王様が、川にいるワニの数を数えたいと言っています。みんな、川に一列に並んでください」。\n\nワニたちは喜んで、川に一列に並びました。カンチルは「一、二、三…」と数えながら、ワニの背中を次々に跳んでいきました。あっという間に、カンチルは川の向こう岸に着きました。\n\n「ありがとう、ワニさんたち。実は、王様は数を数えたいのではありません。わたしは川を渡りたかっただけです」とカンチルは笑いながら言いました。\n\nワニたちは騙されたことに気づきましたが、もうカンチルを捕まえることはできませんでした。カンチルは果樹園で、おいしい果物をたくさん食べることができました。",
                'translated_content' => "Di dekat hutan, ada sebuah sungai besar. Di seberang sungai itu terdapat kebun buah dengan banyak buah yang lezat. Seekor kancil kecil ingin memakan buah-buahan itu.\n\nNamun, di sungai itu tinggal banyak buaya. Para buaya selalu menunggu untuk memangsa kancil. Kancil pun berpikir keras bagaimana caranya menyeberangi sungai itu.\n\nKancil mendapatkan ide bagus. Kancil berkata dengan suara keras kepada para buaya, \"Raja ingin menghitung jumlah buaya di sungai ini. Ayo, semuanya berbaris satu barisan di sungai.\"\n\nPara buaya dengan senang hati berbaris satu barisan di sungai. Kancil pun menghitung sambil berkata, \"Satu, dua, tiga...\", melompat dari punggung satu buaya ke buaya lainnya. Dalam sekejap, kancil sampai di seberang sungai.\n\n\"Terima kasih, teman-teman buaya. Sebenarnya, raja tidak ingin menghitung jumlah kalian. Aku hanya ingin menyeberangi sungai ini,\" kata kancil sambil tertawa.\n\nPara buaya menyadari bahwa mereka telah tertipu, tetapi mereka sudah tidak bisa menangkap kancil lagi. Kancil pun bisa makan banyak buah lezat di kebun buah itu.",
                'items' => $this->glossary([
                    ['果樹園', 'かじゅえん', 'kajuen', 'kebun buah'],
                    ['渡ろうか', 'わたろうか', 'watarouka', 'menyeberang, ya (bentuk ajakan pada diri sendiri)'],
                    ['並んで', 'ならんで', 'narande', 'berbaris (bentuk te)'],
                    ['跳んで', 'とんで', 'tonde', 'melompat (bentuk te)'],
                    ['騙された', 'だまされた', 'damasareta', 'tertipu (bentuk pasif lampau)'],
                ]),
            ],
            [
                'title' => 'カンチルのきゅうり泥棒',
                'slug' => 'membaca-jepang-kancil-mencuri-timun',
                'level' => 'N5',
                'summary' => '空腹なカンチルがきゅうり畑で樹液の罠にはまってしまう、ヌサンタラの動物寓話。',
                'minutes' => 10,
                'xp' => 30,
                'content' => "夜、お腹がすいたカンチルは、農家のきゅうり畑にこっそり入りました。畑には、よく熟したきゅうりがたくさんありました。\n\nカンチルは大喜びで、きゅうりをたくさん食べました。次の日の朝、農家の人は畑のきゅうりが減っていることに気づきました。「誰かがわたしのきゅうりを盗んでいる」と農家の人は怒りました。\n\n農家の人は、木の樹液を使って、人の形をした人形を作りました。その人形はまるで本物の見張り番のようでした。農家の人はその人形を畑の真ん中に立てました。\n\nその夜、カンチルはまた畑にやって来ました。畑に立っている人形を見て、カンチルは「そこにいるのは誰だ。きゅうりを食べてもいいか」と聞きました。しかし、人形は何も答えませんでした。\n\nカンチルは怒って、「返事をしろ」と言いながら、人形を手で叩きました。すると、カンチルの手は樹液にくっついてしまいました。カンチルはもっと怒って、足でも蹴りましたが、足もくっついてしまいました。\n\n次の朝、農家の人が畑に来ると、樹液の人形にくっついたカンチルが動けなくなっていました。こうして、カンチルはついに捕まってしまいました。",
                'translated_content' => "Pada malam hari, kancil yang lapar diam-diam masuk ke ladang timun milik seorang petani. Di ladang itu terdapat banyak timun yang sudah matang.\n\nKancil sangat senang dan memakan banyak timun. Keesokan paginya, petani itu menyadari bahwa timun di ladangnya berkurang. \"Seseorang telah mencuri timunku,\" kata petani itu dengan marah.\n\nPetani itu menggunakan getah pohon untuk membuat sebuah boneka berbentuk manusia. Boneka itu terlihat seperti penjaga sungguhan. Petani itu menempatkan boneka itu di tengah-tengah ladang.\n\nMalam itu, kancil datang lagi ke ladang. Melihat boneka yang berdiri di ladang, kancil bertanya, \"Siapa itu di sana? Bolehkah aku memakan timun ini?\" Namun, boneka itu tidak menjawab sama sekali.\n\nKancil marah dan berkata, \"Jawab aku,\" sambil memukul boneka itu dengan tangannya. Tangan kancil pun menempel pada getah pohon itu. Kancil semakin marah dan menendangnya dengan kaki, tetapi kakinya pun ikut menempel.\n\nKeesokan paginya, ketika petani datang ke ladang, ia menemukan kancil yang tidak bisa bergerak karena menempel pada boneka bergetah itu. Dengan demikian, kancil pun akhirnya tertangkap.",
                'items' => $this->glossary([
                    ['熟した', 'じゅくした', 'jukushita', 'matang (bentuk lampau)'],
                    ['盗んで', 'ぬすんで', 'nusunde', 'mencuri (bentuk te)'],
                    ['樹液', 'じゅえき', 'jueki', 'getah pohon'],
                    ['見張り番', 'みはりばん', 'mihariban', 'penjaga'],
                    ['くっついて', 'くっついて', 'kuttsuite', 'menempel (bentuk te)'],
                    ['蹴りました', 'けりました', 'kerimashita', 'menendang (bentuk lampau)'],
                ]),
            ],
            [
                'title' => 'アンデアンデ・ルムット',
                'slug' => 'membaca-jepang-ande-ande-lumut',
                'level' => 'N4',
                'summary' => '王子が変装し、心優しいクレティン・クニンを見つけ出す、東ジャワの伝説。',
                'minutes' => 12,
                'xp' => 30,
                'content' => "昔、東ジャワに、アンデアンデ・ルムットという若者がいました。実は彼は王子でしたが、身分を隠し、貧しい若者のふりをして、本当に自分を愛してくれる女性を探していました。\n\n一方、ある村に、クレティン・クニンという娘がいました。彼女は継母と三人の姉に意地悪をされ、いつも家の仕事ばかりをさせられていました。それでも、クレティン・クニンは優しく、素直な心を失いませんでした。\n\nアンデアンデ・ルムットが結婚相手を探しているという噂が村に届くと、三人の姉たちは美しい服を着て、化粧をして、彼に会いに出かけました。彼女たちはクレティン・クニンを家に残し、一緒に連れて行こうとはしませんでした。\n\nクレティン・クニンも本当はアンデアンデ・ルムットに会いに行きたいと思っていました。すると、一羽の不思議な黄色い鳥が現れ、彼女に道を教え、櫛を一本くれました。「この櫛はきっとあなたを助けてくれます」と鳥は言いました。\n\n道の途中には大きな川があり、恐ろしいカニの化け物が番をしていました。カニの化け物は川を渡る者に「わたしにキスをしなければ渡らせない」と言い、三人の姉たちは仕方なくキスをして、川を渡りました。\n\nクレティン・クニンの番になると、彼女は鳥にもらった櫛を川に投げ入れました。すると、川の水が両側に分かれ、クレティン・クニンはキスをすることなく、きれいなまま川を渡ることができました。\n\nアンデアンデ・ルムットの家に着くと、彼は三人の姉たちを見て、「あなたたちの体からはカニの匂いがする」と言い、結婚を断りました。最後に、泥だらけで質素な服を着たクレティン・クニンが到着すると、アンデアンデ・ルムットは彼女の清らかな心に気づき、結婚を申し込みました。\n\nこうして、アンデアンデ・ルムットとクレティン・クニンは結婚しました。この物語は、見た目の美しさよりも、心の美しさが大切だということを教えてくれます。",
                'translated_content' => "Dahulu kala, di Jawa Timur, hiduplah seorang pemuda bernama Ande-Ande Lumut. Sebenarnya ia adalah seorang pangeran, tetapi ia menyembunyikan jati dirinya dan menyamar sebagai pemuda miskin untuk mencari seorang perempuan yang benar-benar mencintainya dengan tulus.\n\nSementara itu, di sebuah desa, hiduplah seorang gadis bernama Kleting Kuning. Ia diperlakukan dengan jahat oleh ibu tirinya dan ketiga kakak tirinya, dan selalu dipaksa mengerjakan pekerjaan rumah. Meski begitu, Kleting Kuning tetap memiliki hati yang lembut dan tulus.\n\nKetika kabar bahwa Ande-Ande Lumut sedang mencari calon istri sampai ke desa itu, ketiga kakak tirinya mengenakan pakaian indah dan berdandan, lalu pergi menemuinya. Mereka meninggalkan Kleting Kuning di rumah dan tidak mengajaknya pergi bersama.\n\nKleting Kuning sebenarnya juga ingin pergi menemui Ande-Ande Lumut. Tiba-tiba, muncullah seekor burung kuning yang ajaib, menunjukkan jalan kepadanya, dan memberinya sebuah sisir. \"Sisir ini pasti akan menolongmu,\" kata burung itu.\n\nDi tengah perjalanan, terdapat sebuah sungai besar yang dijaga oleh seekor kepiting raksasa yang menakutkan. Kepiting raksasa itu berkata kepada siapa pun yang ingin menyeberang, \"Aku tidak akan membiarkanmu menyeberang kecuali kau menciumku,\" dan ketiga kakak tirinya pun terpaksa menciumnya untuk menyeberangi sungai.\n\nKetika giliran Kleting Kuning tiba, ia melemparkan sisir pemberian burung itu ke sungai. Seketika, air sungai terbelah menjadi dua sisi, dan Kleting Kuning pun bisa menyeberangi sungai dengan bersih tanpa harus mencium kepiting itu.\n\nSetibanya di rumah Ande-Ande Lumut, ia melihat ketiga kakak tiri itu dan berkata, \"Tubuh kalian berbau kepiting,\" lalu menolak untuk menikahi mereka. Terakhir, ketika Kleting Kuning tiba dengan pakaian sederhana yang penuh lumpur, Ande-Ande Lumut menyadari kemurnian hatinya dan melamarnya untuk menikah.\n\nDemikianlah, Ande-Ande Lumut dan Kleting Kuning pun menikah. Kisah ini mengajarkan kita bahwa keindahan hati jauh lebih penting daripada keindahan penampilan luar.",
                'items' => $this->glossary([
                    ['身分を隠し', 'みぶんをかくし', 'mibun wo kakushi', 'menyembunyikan identitas'],
                    ['意地悪をされ', 'いじわるをされ', 'ijiwaru wo sare', 'diperlakukan jahat (bentuk pasif)'],
                    ['噂', 'うわさ', 'uwasa', 'gosip/kabar'],
                    ['櫛', 'くし', 'kushi', 'sisir'],
                    ['番をして', 'ばんをして', 'ban wo shite', 'berjaga (bentuk te)'],
                    ['泥だらけ', 'どろだらけ', 'dorodarake', 'penuh lumpur'],
                    ['清らかな', 'きよらかな', 'kiyorakana', 'murni/suci'],
                ]),
            ],
        ];
    }
}
